### ISSUE TITLE
Custom field name

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#10]
As a form can become fairly long. Having the option to add a custom name field might be helpful.
The user would then be able to rename each field as they want.

Can be useful in a future conditionals as well as the Email Builder. 
Conditionals and the E-mail Builder it would be easier to use the correct field. If there are 4-5 fields called name it would be difficult to know which is what.

![Gutenberg-Forms-Custom-Name-Field](https://user-images.githubusercontent.com/5323259/74460016-8ad7ae00-4e8c-11ea-8f70-bc0a03a57688.jpg)

**Comment by munirkamal** [comment]
I don't think it's needed? As we already have form labels that are editable and already used to recognizable in the email builder when try to insert form data there.

Why would one have 4-5 name fields with the exact same label "Name". I understand there could be fields like.

First Name
Last Name
Father Name
Mother Name
Child Name
etc.

So they all will be different and recognizable? Am I missing some use case for this?

Adding an option is not an issue, I just don't want to understand that it a must-have option that many would need.

**Comment by paaljoachim** [comment]
> So they all will be different and recognizable? 

Yes. It would be easier to use the Email Builder being able to recognize the different Name fields.
Ahhh I can change the name directly in the field layout and notice that it also changes in the Email Builder drop down (popup). But it still has the same name field in the Body area.

Conditionals (thinking later on). It would be easier using conditionals when one knows which field one is doing something with. If the conditionals use the renamed field name similar to the drop down (popup) for the Email Builder then that works fine.

The only issue I have at the present time is having 4-5 name fields in the body area of the Email Builder.

**Comment by munirkamal** [comment]
This should be working fine? The field labels (which are editable) servers as the field name as well which are recognizable in the email builder, conditional options, etc.

Closing it for now, let me know if there is something missing?

**Comment by paaljoachim** [comment]
If needed I will get back to this at a later time. Good job..:)
