### ISSUE TITLE
Gutenberg 7.9 RC bug: Creating Reusable block in Twenty Twenty duplicates toolbar icons

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#101]
**Describe the bug**
After having created a Reusable Block in Twenty Twenty the toolbar icons are duplicated. Creating another Reusable Block another set of icons are added 3x icons. Creating a 4th Reusable Block there becomes 4x toolbar icons.

Deactivating Gutenberg Forms also removes the weird bug.

**To reproduce**
1. Be sure that Gutenberg Forms is active
2. Go to create a Reusable block. Click the 3 dots and choose "Add to Reusable blocks."
3. Click the empty paragraph block area below it.
4. Check out the paragraph toolbar.

**Expected behavior**
I expected the toolbar not to change because of adding a reusable block.

**Screenshots**
![Reusable-Block-Test](https://user-images.githubusercontent.com/5323259/79195317-581b4900-7e2e-11ea-8905-dbf2033be7e1.gif)

**Desktop (please complete the following information):**
OSX 10.15.4
Chrome
Desktop Server
Gutenberg version 7.9 RC

**Comment by munirkamal** [comment]
@paaljoachim 

I just installed the 7.9 RC and tested it out but unable to replicate the issue you are getting. I also have Gutenberg forms plugin installed and active.

![Screen Recording 2020-04-14 at 06 28 PM](https://user-images.githubusercontent.com/5817882/79230353-e539be80-7e7d-11ea-94df-4b2245a8153e.gif)

Can you please check this again? Maybe some other plugin causing this and not Gutenberg Forms? Try on a fresh test website main be?

Let me know.

**Comment by munirkamal** [comment]
@paaljoachim 

Ok, now I am able to replicate this issue. But it is not related to Gutenberg Forms. This even happens when you deactivate the Gutenberg Forms plugin. 

I am assuming this bug is with this Gutenberg plugin update itself.
