### ISSUE TITLE
Showing field titles in form submission instead of field data names.

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#107]
I just tested the new notification area located in the sidebar.

![Screen Shot 2020-04-15 at 18 06 21](https://user-images.githubusercontent.com/5323259/79360428-32806380-7f44-11ea-8032-cef8febc04ba.png)

Here is the e-mail I received in my hotmail inbox.
![Screen Shot 2020-04-15 at 18 09 32](https://user-images.githubusercontent.com/5323259/79360488-47f58d80-7f44-11ea-88fa-e9b7c0f160dd.png)

It shows the field data name.
It would be better to have a default to show the field names.

Default looks like this:

name_fd8bec: Paal Joachim Romdahl
email_986635: paaljoachim@hotmail.com
message_a5d613: A test

So instead have it show like this:
Name: Paal Joachim Romdahl
email: paaljoachim@hotmail.com
message: A test

**Comment by munirkamal** [comment]
@paaljoachim 

**Hard to implement.** 

This is how all the forms work I suppose. This is why we have added a form ID option for each field block. So simply change the id to something better and it will be used in there automatically.

![Image 2020-04-15 at 9 16 14 PM](https://user-images.githubusercontent.com/5817882/79361246-797b5280-7f5e-11ea-9fda-5d8d29ab36c1.png)


So you can change your  `name_fd8bec` to `Name` and  `email_986635` to `Email` and you get it like you want. 

Try and let me know please.

**Comment by paaljoachim** [comment]
Ahhh....

That is a nice tips to know about. That worked well! Tips for the docs.

It now looks like this:
![Screen Shot 2020-04-15 at 18 35 23](https://user-images.githubusercontent.com/5323259/79363237-f2bb7b00-7f47-11ea-8013-274c3bc6bb74.png)

Thanks Munir!

**Comment by munirkamal** [comment]
Yeah I know we need Docs badly now to onboard users and help them understand how things work.

**Comment by paaljoachim** [comment]
What if we just create a new document Google etc as a way to get documentation started? Then multiple people can share tips/advice on how to do various things into it, and that can be ported over to an online documentation on a fitting web site.

**Comment by macemmek** [comment]
> So you can change your name_fd8bec to Name and email_986635 to Email and you get it like you want.

It works until I need to send a multi-word label with spaces...

**Comment by munirkamal** [comment]
> > So you can change your name_fd8bec to Name and email_986635 to Email and you get it as you want.
> 
> It works until I need to send a multi-word label with spaces...

spaces replaced with an underscore for a reason and I suppose this is still readable and does the job fine.
