### ISSUE TITLE
Changing the name to only using Gutenberg Forms in the WP repo and Add plugins screen.

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#108]
Doing a search in the add a new plugin screen.

![Screen Shot 2020-04-15 at 23 36 44](https://user-images.githubusercontent.com/5323259/79391571-12679900-7f72-11ea-962f-a1afad3af478.png)

The name: WordPress Form Builder Plugin - Gutenberg Forms.

Here is an option:

![Gutenberg-Forms-Add-Plugins-screen](https://user-images.githubusercontent.com/5323259/79392034-ef89b480-7f72-11ea-9cd7-9448f4e603a7.jpg)

Changing to only using the name: Gutenberg Forms

Main reason is that it looks a lot cleaner with the shorter name. It also seems like an official core plugin.

**Comment by munirkamal** [comment]
@paaljoachim  That is for SEO purpose as discussed earlier. It appears like this in search results only at WP plugins or Search engines, etc.

On the WP admin area, it only says Gutenberg Forms as per your earlier suggestion.

I want to keep it this way for taking SEO advantage.

**Comment by paaljoachim** [comment]
Alright.
