### ISSUE TITLE
Option to disable certain form actions

### ISSUE THREAD

**Issue by munirkamal** [munirkamal/gutenberg-forms#110]
As per a suggestion via the WP forum, we may add options to disable:

* Email Notification
* Saving Entries to DB

https://wordpress.org/support/topic/feature-request-api-access-to-email-trigger/

**Comment by paulgibbs** [comment]
A developer will need an action they can hook into to handle saving entries themselves.

An example use case might be I want to send form data to a CRM system.

**Comment by paulgibbs** [comment]
Can we get a do_action() at the bottom of `sendMail()` with all the data so I can add in my own handling, please?
