### ISSUE TITLE
Hidden Field Block

### ISSUE THREAD

**Issue by munirkamal** [munirkamal/gutenberg-forms#113]
Add a hidden field. Review and discuss what options it should have.

**Comment by munirkamal** [comment]
Hidden field may also contain default values as defined while creating the form..

**Comment by macemmek** [comment]
Hi, I'd like to add a little extra bit: a common use case for hidden fields is to carry some dynamic information like that from a specific GET attribute in the url.

**Comment by ZafarKamal123** [comment]
I've included the hidden field block in the latest commit with Tag Inserter ( can be used for inserting dynamic information in the hidden field ). 👍

**Comment by ZafarKamal123** [comment]
A quick look on the new tag inserter. That is added to the hidden field and email notification options.

![capture](https://user-images.githubusercontent.com/48084051/85203446-5d61ac00-b327-11ea-9ceb-d26217b4d119.PNG)
