### ISSUE TITLE
Docs site cannot be reached

### ISSUE THREAD

**Issue by yura-x** [munirkamal/gutenberg-forms#122]
Hello! Thank you for your great plugin.
It seems that Docs link going to nowhere in the Plugin Settings page:
[http://docs.gutenbergforms.com/](http://docs.gutenbergforms.com/)
[https://prnt.sc/s8e7f0](https://prnt.sc/s8e7f0)

**Comment by munirkamal** [comment]
Hi,

Yeah, that is yet not there. I will be preparing it soon. 

Thanks
