### ISSUE TITLE
'type' attributes for input fields

### ISSUE THREAD

**Issue by yura-x** [munirkamal/gutenberg-forms#123]
It seems that text field does not have `type="text"` attribute.
And phone field does not have `type="tel"` attribute.
If you're styling your fields via `[type="text"]` selector this will not be styled

Also select field has `type="select"` which is not valid markup.

Thank you!

**Comment by munirkamal** [comment]
Hi @yura-x 

Thank you to report that. I will double check all the input attributs.

Thanks
