### ISSUE TITLE
Try optimization - memory RAM usage increased

### ISSUE THREAD

**Issue by marceloaof** [munirkamal/gutenberg-forms#125]
Hello.

Memory RAM usage is escalating very quickly. ⚠ For a plugin centered on blocks, I suppose your approach has everything to be faster than other form plugins. However, at the moment, 805.18 kiB was very noticeable on page loading as soon as I activated Gutenberg Forms. It is not good. Please, reconsider dependencies you are using or code you are adding. Freemius normally is the problem on other plugins, but I don´t know if Freemius is the reason for suddenly increase on RAM usage, because so much was added on latest updates. (Congratulations, by the way)

Of course memory RAM is not the only variable in performance, but still **much** could be optimized.

Version 1.3 uses [805.18 KiB](https://plugintests.com/plugins/forms-gutenberg/1.3.0) of memory.
- Admin Page Using Gutenberg Components
- Default validation Messages in admin page
- From Field in the Email Notification Builder
- All Data tag in the Email Notification Builder
- Form Actions – Now you can enable/disable any action like form entries, email notification etc
- Freemius

Version 1.2 uses [106.13 KiB](https://plugintests.com/plugins/forms-gutenberg/1.2.0) of memory.
- Now form entries are recorded in database
- forms CPT – Create forms and use anywhere using shortcode
- Templates Library – Start creating forms quickly with ready to use templates
- Bulk Add Option for select, radio and checkbox fields

Version 1.1 uses [13.98 KiB](https://plugintests.com/plugins/forms-gutenberg/1.1.0) of memory.
- Multi Step feature
- File Upload Field
- Min / Max Length for Text and Message Fields
- Option To Hide Form On Success

Version 1.0.9 and previous versions were so well-made, that the forms used to work with an insignificant memory usage: [around 0 KiB](https://plugintests.com/plugins/forms-gutenberg/1.0.9).

I understand if more resources are needed for complex features, but from 0 to 800? You see my point?

Competitors:
Contact Form 7: 318.81 KiB.
Fluent Forms: 588.86 KiB.
Formidable Form Builder: 455.17 KiB.
PlanSo Forms: 157.26 KiB.
Ninja Forms without add-ons: 1.630 KiB.

Elementor is much bigger in scope. Yet, its memory usage is: 1.110 KiB.

**Comment by munirkamal** [comment]
Hi @marceloaof 

Thank you for bringing this. We have tried to make code as much optimized possible, however this is something we need to keep improving. I will definitely look into this.

In the last Update, we have integrated Freemius, so that must have made a significant difference, I am presuming. 

I will keep this ticket open and comeback on this after adding a few more planned features/bug fixes. 

Rest assures, this is something very important and we will do best to optimize the code as much possible.

Regards,
Munir

**Comment by ZafarKamal123** [comment]
The ram usage in v 1.3.0 was around 800KB due to freemius integrations. Therefore we have removed freemius in the v1.4.0 and the memory usage is around [161KB](https://plugintests.com/plugins/forms-gutenberg/latest). Therefore closing this issue for now 👍
