### ISSUE TITLE
Rename Uploaded Files on submission

### ISSUE THREAD

**Issue by marceloaof** [munirkamal/gutenberg-forms#126]
An idea:

When you upload files using Gutenberg forms, the name of the uploaded file changes on submission to a random name.

This is done as a security measure, to protect your site from external threats. It is a commonly used method for increasing form security, and is used by many form plugins.

This implementation is common when the file is stored on server. However, some form plugins also apply this rule when the file is sent by e-mail.

**Comment by munirkamal** [comment]
Hi @marceloaof 

Well, that is already in place. We are changing the filename already for all the uploaded files. 
https://www.loom.com/share/5170f3d4fb8f4c218ca11883d70f9562

Am I missing your point? Or this is exactly what you meant?
