### ISSUE TITLE
New icon for Calculation block

### ISSUE THREAD

**Issue by marceloaof** [munirkamal/gutenberg-forms#128]
Hello.
The icon for "Calculation" block inside a Gutenberg form is strange:
![image](https://user-images.githubusercontent.com/61061987/81015605-59400480-8e35-11ea-95d5-b086734e22c0.png)

It is the same icon used on the "File" block.
Instead of a sheet of paper, possibly is going to serve you better an "%" or "+ - / x" icon.

Examples:
![image](https://user-images.githubusercontent.com/61061987/81015564-46c5cb00-8e35-11ea-8a0c-e92597b13214.png)

**Comment by munirkamal** [comment]
Hi,

Thank you for raising this as well, these small details are important to notice. I appreciate your time in creating these issues.

Adding it to the To-Do list as well.
