### ISSUE TITLE
Rename plugin

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#13]
Hey

On the WordPress repo the name of the plugin is:
"WordPress Form Builder Plugin – Gutenberg Forms"

Rename to

"Gutenberg Forms"

This will also change the name in the installed plugins screen.
![Screen Shot 2020-02-16 at 09 45 01](https://user-images.githubusercontent.com/5323259/74601853-dcf21c80-50a2-11ea-9c82-336703f66074.png)

Btw
Do also soon create a Github repo for the Block Slider plugin. 
This also needs to be renamed.

**Comment by munirkamal** [comment]
@paaljoachim 

That is done intentionally to make in regards to SEO. I followed the advice by the Freemius on this.
https://freemius.com/blog/seo-on-new-plugin-repository/

Slider to be focused a bit later. Let's focus only on this one for at least a month to have it all the must needed features comparing to a couple of top free plugins in the WP repo.

**Comment by munirkamal** [comment]
Will change it for "Plugins Admin Screen" and maybe rename it as well too in general.

General:
Gutenberg Forms - WordPress Form Builder Plugin

WP Admin:
Gutenberg Forms
