### ISSUE TITLE
Adding Form Entries via WordPress REST API

### ISSUE THREAD

**Issue by darbymanning** [munirkamal/gutenberg-forms#131]
Hey,

I've just discovered this plugin, looks really great - and thanks! Looking over the repo I can see that Form Entries is quite a new bit of functionality. I just wondered if there was a way at present to programmatically add an entry via the WP REST API? Sorry if I've missed this in any documentation etc!

**Comment by munirkamal** [comment]
@darbymanning 

Technically the Form Entries is a CPT and you should be able to manipulate it via Rest API the same way you would do to any WP CPT.  Let me know if there is an issue with that.

Btw, what is the use-case of doing it?

**Comment by darbymanning** [comment]
Ah sure, that makes sense. I'll see how I get on.

Use-case: I'm building a site with SPA using [Svelte](https://svelte.dev/), so I'm using the WP REST API to render the forms to the user, and mailgun to actually send the message. So I also need to add the entry to the db manually via the API.
