### ISSUE TITLE
Issue with the new Form Action option

### ISSUE THREAD

**Issue by munirkamal** [munirkamal/gutenberg-forms#132]
If we remove the email notification action, it also doesn't save form entries. 

Also, change label Add Item to "**Add/Remove Actions**"
![Image 2020-05-05 at 5 33 00 PM](https://user-images.githubusercontent.com/5817882/81066438-87394d80-8ef6-11ea-910b-15affc22699d.png)

**Comment by ZafarKamal123** [comment]
This issue is now fixed, In the latest commit.
