### ISSUE TITLE
Installed Plugins screen: Add-Ons - Opt In

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#137]
Chrome
Local dev site
WP 5.4
Gutenberg plugin 8.1.0 RC

Clicking Add-Ons lead to this page:
![Screen Shot 2020-05-13 at 10 02 07](https://user-images.githubusercontent.com/5323259/81787089-d6880b00-9500-11ea-9169-5dcdfc5aa40a.png)

Clicking Opt-in leads to this page:
![Screen Shot 2020-05-13 at 10 02 51](https://user-images.githubusercontent.com/5323259/81787164-ec95cb80-9500-11ea-9e82-45643ac25022.png)

Standard Installed plugin options are:
Activate/Deactivate and Settings. 

At this stage and time there is no need to have Add-Ons link. Add a Settings link instead which goes to the Dashboard screen.
Opt In is likely added by Freemius. So one can not remove it. If you can then please also remove it from here.

(Personally I find Freemius invasive with their different screens and would not use it.)

**Comment by munirkamal** [comment]
Yeah, I will think about removing freemium integration as it seems a bit heavy. However, it does some good work for stats and when we will have pro version it is a good option. 

But, I think I may remove it for now.
