### ISSUE TITLE
Shorten Styles preview

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#138]
Hey

I am seeing this for a long form that I have:
![Screen Shot 2020-05-13 at 10 51 29](https://user-images.githubusercontent.com/5323259/81792026-c6bff500-9507-11ea-8514-8ea86e20834b.png)

Cut it off after a certain length. Styles is just meant to give a preview of what it can look like. The user can easily just click a style and see what it looks like in the Gutenberg layout screen. No need to show most of the form. Keep it shorter.

**Comment by munirkamal** [comment]
Hey @paaljoachim ,

Nice to see your feedback again. 😇

Well, this is actually handled by Gutenberg itself, I am not sure if we can manipulate it. This seems not possible with the available APIs.

🤔

**Comment by paaljoachim** [comment]
Good to be giving feedback again Munir..:)

Seems like a regular Gutenberg issue is needed.

What we need is a max length for styles.

**Comment by munirkamal** [comment]
Yeah, I suppose you should raise this with them, this is a good example of how long it can be with long content. And if there is already a solution for this then let me know, please.

**Comment by paaljoachim** [comment]
Or just bring it up during the Open Floor section of todays Core Editor chat.

**Comment by munirkamal** [comment]
What it is today?

**Comment by paaljoachim** [comment]
Check here:
https://make.wordpress.org/core/2020/05/12/editor-chat-agenda-13-may-2020/

**Comment by munirkamal** [comment]
Ahh.. That is 7:00 PM my time. Won't be available that time.

**Comment by munirkamal** [comment]
Ok, I've create an issue there. If you can raise it to open-floor that would be good.

**Comment by paaljoachim** [comment]
What you can do is add a comment to the agenda post. Mention the issue and whatever else, and it will be raised by the facilitator during the chat.

**Comment by munirkamal** [comment]
So as per the discussion from slack, it can be improved if we add preview content to form blocks. I've created another issue #143 for that, so I am closing this one.
