### ISSUE TITLE
Form Action is confusing

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#139]
I was working on styling the default button which again would style the Another Submission and happen to notice the...

![Screen Shot 2020-05-13 at 10 55 29](https://user-images.githubusercontent.com/5323259/81792464-62516580-9508-11ea-8413-ede80eca7800.png)

Form Action area. Which looks like tags. There is no clear message how the Form Action works. 
What is it?
How does it work?
What options are available?

It needs to be clear how this works and the options present.

**Comment by munirkamal** [comment]
We may add some instructions to it.

**Comment by paaljoachim** [comment]
The Tags style might not be the correct way to handle it.... perhaps a kind of category style might be better as it would show available options.

**Comment by ZafarKamal123** [comment]
@paaljoachim there will be many more actions in future like mailchimp, mailpoet etc. Therefore the tags seems to be an organized solution.

**Comment by paaljoachim** [comment]
Ok.

This PR is made to make tags more visible again.
https://github.com/WordPress/gutenberg/pull/21859

**Comment by ZafarKamal123** [comment]
That's awesome! 👌

**Comment by ZafarKamal123** [comment]
Closing it for now!. Let me know if the tag component improved

**Comment by paaljoachim** [comment]
Btw here is what Youtube are doing. Click into the field line and have a drop down show up.
![Screen Shot 2020-05-25 at 14 31 56](https://user-images.githubusercontent.com/5323259/82813212-e6a2d180-9e94-11ea-95c5-c647baf1b6f2.png)
