### ISSUE TITLE
Form columns - not able to change amount of columns used.

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#14]
Hi

I added a Form column:
![Screen Shot 2020-02-16 at 10 06 21](https://user-images.githubusercontent.com/5323259/74601960-15462a80-50a4-11ea-9f30-605309af4d08.png)

Using 3 columns. But I am not able to change the amount of columns in the sidebar.

**Comment by munirkamal** [comment]
We will implement options for this. 👍

**Comment by munirkamal** [comment]
There is some technical limitation that I need to explore. Putting it on hold for time being.
