### ISSUE TITLE
How to style default Form button?

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#140]
I clicked the default Form button.
![Screen Shot 2020-05-13 at 11 00 28](https://user-images.githubusercontent.com/5323259/81792919-fd4a3f80-9508-11ea-90e5-b4e9aa62c1f5.png)

It selects the full form. (Which I remember from earlier.)
I look in the sidebar options for a way to style the button. Kinda like a section named Button where all the information that involves the button would be such as:
Disable Submit Button (in smaller text to "add your own button".)
Button Alignment
Button text color
Button background color
Button border radius (to round it)

**Comment by paaljoachim** [comment]
Actually a better way would be to include a Form button in the standard form. Include that like any other field when the user selects to include a "Standard" form.
As there would not be a built in / default button. The default button would be a Gutenberg Form button.

**Comment by munirkamal** [comment]
@paaljoachim 

currently, the default form button and fields are styled via the Form Design pannel.
![Image 2020-05-14 at 3 20 49 PM](https://user-images.githubusercontent.com/5817882/81923392-0a455c80-95f7-11ea-985c-2d8679383d74.png)


But, I think you are correct we can do this.

1) Add Button Background Color Option (may be other options as you suggested).
2) For the Standard Form Template, we replace the default button with the Form Button block.
