### ISSUE TITLE
Premium: Create WooCommerce cart and checkout pages

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#144]
Hey Munir

It would be great to have a Gutenberg form of the cart and checkout pages  for WooCommerce in a premium version of the plugin (+ whichever other pages are needed). As one would be able to move them around and add/remove various fields.

**Comment by munirkamal** [comment]
@paaljoachim 

That seems a nice idea, however, WooCommerce itself making the checkout/cart pages block-based.

Read more about it here.
https://woocommerce.wordpress.com/2020/05/27/available-for-testing-a-block-based-woocommerce-cart-and-checkout/

What do you think after that info?

**Comment by paaljoachim** [comment]
Yeah. That is where I got the idea from. At the moment there is a lot of focus on the design. There are a very few options to what can be adjusted. But this is likely something that will gradually change over some time.

**Comment by munirkamal** [comment]
@paaljoachim 

Obviously that is just the very beta version of Block-Based checkout & cart by Woo. And they will gradually enhance the customization and make it better.

I think let's hold this idea for a while and see what they are coming up with. And what they plan. 🙂

**Comment by paaljoachim** [comment]
Yeah. I'll just close this issue for now..:)
