### ISSUE TITLE
Editor - Column view and blocks

### ISSUE THREAD

**Issue by Torbanio** [munirkamal/gutenberg-forms#147]
Dont know if it is on purpose, but blocks in a column like name, buttons, selects, radiobuttons should be - in my opinion - on the same level in a row, otherwise forms not gonna be look straight. 
![form](https://user-images.githubusercontent.com/66257115/83419020-b58e4800-a424-11ea-8353-3bcd66697c8e.jpg)

And submit button needs some footer space in editor. Next block touches submit button. 
![button](https://user-images.githubusercontent.com/66257115/83419037-bb842900-a424-11ea-9a00-c7bee482464c.png)

**Comment by munirkamal** [comment]
That is up to a user to structure/layout a form. We are not imposing any such stylings on the form. In fact, the form depends mostly on the theme you use for the styling (like the core blocks).

So for instance, you can use a spacer block to make the fields sit aligned with other columns as you wish. We cannot impose this by default for one use case, as others may not need it like this.

Closing this issue, for now, feel free to put more light on this use case and we may continue the discussion on this.
