### ISSUE TITLE
Help Text 

### ISSUE THREAD

**Issue by Torbanio** [munirkamal/gutenberg-forms#148]
Formfield: Inline Help or below formfield would be nice.

**Comment by munirkamal** [comment]
@Torbanio 

Do you mean the field description? 

If that is what you mean, isn't it already possible to add a paragraph block where ever you like (above/below any field) and write your help text/description?

Remember, the goal for this plugin is to utilize the Gutenberg editor and make it as much flexible as possible using Gutenberg blocks in combination with form field blocks. You need to think out of the traditional form plugins' way. 😇

Let me know.

**Comment by Torbanio** [comment]
yes meant field description.... dont know if a paragraph block would be close enouph. Handling would be more difficult. But sure, could also be a solution.

**Comment by munirkamal** [comment]
Paragraph block would be more flexible approach, you can use it anywhere and actually not just paragraph, you may use any block for that matter to display some info about a particular form question/field. 

Closing this issue for now.
