### ISSUE TITLE
Keep data after next button

### ISSUE THREAD

**Issue by Torbanio** [munirkamal/gutenberg-forms#149]
Data should be available for return visitors. Means users do not have to type in all formfields again which were typied in e.g. one day before.

**Comment by munirkamal** [comment]
@Torbanio 

Do you mean to keep data for unsubmitted forms? Does that also mean the possibility to save the partially filled form?

**Comment by Torbanio** [comment]
Yes, thats what I meant. A unsubmitted form should be saved for a while.

**Comment by munirkamal** [comment]
ok. This is something for the future, I have some ideas for this feature and this is not in the current priority span. 

I am closing this for now, as I have something similar in a future planned features list already. Don't worry this is something I will eventually bring with form abundant notification, etc. 😇
