### ISSUE TITLE
Adding form columns inside a group?

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#15]
It does not work to add the Form Columns Block inside a Group Block.

**Comment by munirkamal** [comment]
Try Form Group Block which has been added as a native replacement to the default Group block. The Form Group block has advantages over that.

1) The HTML markup of form Group block is set at <fieldset> which is as per the markup standards for a web form.
2) When we will implement conditional logic, we will make it possible to conditionally show/hide a "Form Group" as well.

You can, however, use the default Group block to add static content within form block. And then use default columns block inside the default group block for that purpose.

**Comment by paaljoachim** [comment]
When I tested the plugin a bit earlier I noticed that I was not able to add the Form column into the Form group. But when testing it a moment ago I got it working. 

I noticed that the group block begins with a grey background. As you mentioned on Facebook direct messaging it had to do with showing the user that it is a group block. It is easy enough to change the background color.

The Group block has a title.

![Screen Shot 2020-02-16 at 10 52 00](https://user-images.githubusercontent.com/5323259/74602613-db2c5700-50aa-11ea-86b1-9f23752561b2.png)

It gives the user a chance to give the group block a title which can be good for gathering specific sections of a form.

I added 3 columns into it.

Here is what it looks like on the frontened:

![Screen Shot 2020-02-16 at 10 53 27](https://user-images.githubusercontent.com/5323259/74602631-0151f700-50ab-11ea-8365-0ed7d369a44e.png)

It shows a gap where the My Group title was.
It also shows a border around the group. --> A border around the group should be optional.

**Comment by paaljoachim** [comment]
Actually the Group block could have some additional sidebar settings. 
Border thickness. Border color. Rounded corners. But then again these might not be used at all.

**Comment by munirkamal** [comment]
Thank you to report that. As the group block is using tag `<fieldset>` that is why you see that border as that is how browsers display a fieldset by default.

The Title of the group actually serves as `<legend>` of this fieldset. And when you have an empty legend that is why you are seeing the empty space/gap there.

Here are the details of how this is structured.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset

I am trying to follow the best web standards to output the form markup to make it compatible everywhere. I am also not adding any custom CSS/Styling for the form (unless must needed) by default.

But I do have additional styles. I need to add additional styles for the group.
