### ISSUE TITLE
More Conditionrules

### ISSUE THREAD

**Issue by Torbanio** [munirkamal/gutenberg-forms#150]
Conditions should be more flexible:

1) "Show if" or "Show not if"

2) More rules

![Condition](https://user-images.githubusercontent.com/66257115/83688483-cc33cb00-a5ed-11ea-8fd9-f308ab02c6a1.png)

**Comment by munirkamal** [comment]
Yeah, there will be possibly an advanced conditional logic add-on that will bring more power to the form. The current conditional logic in the free is there to cover the most basic needs by most of the users.

This is also in my planned list of features which may be a separate add-on.
