### ISSUE TITLE
Editor View in columns

### ISSUE THREAD

**Issue by Torbanio** [munirkamal/gutenberg-forms#151]
Little Editor bug:

Editor: Elements in columns are not on same row level but in Preview everything works fine. 

![column](https://user-images.githubusercontent.com/66257115/83689983-36e60600-a5f0-11ea-9f85-1315cd430552.png)

**Comment by munirkamal** [comment]
This again depends on the theme. I will however do some testing on this.

**Comment by ZafarKamal123** [comment]
I've tested it out in the editor. I think this may vary from theme to theme. I'm closing this issue for now if the issue remains feel free to open again.
