### ISSUE TITLE
Possible Bug as reported.

### ISSUE THREAD

**Issue by munirkamal** [munirkamal/gutenberg-forms#156]
`( ! ) Notice: convert_to_screen(), add_meta_box() was called <strong>incorrectly</strong>. Likely direct inclusion of <code>wp-admin/includes/template.php</code> in order to use <code>add_meta_box()</code>. This is very wrong. Hook the <code>add_meta_box()</code> call into the <code>add_meta_boxes</code> action instead. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 3.3.0.) in /Users/dovy/Local Sites/redux4/app/public/wp-includes/functions.php on line 5167`

![Image 2020-06-16 at 6 54 26 PM](https://user-images.githubusercontent.com/5817882/84783843-12802580-b003-11ea-95dc-e8f439195709.png)

Reported by @dovy

**Comment by ZafarKamal123** [comment]
Hey @dovy,
I'm unable to replicate this issue. Can you please provide some more info regarding the issue?
