### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by ghost** [munirkamal/gutenberg-forms#162]
★Hello★

I used Gutenberg Forms a long time ago, on 1.2 and 1.3.
Since then, I removed all forms and entries, and deactivated the plugin, waiting it to be updated.

Today, I updated the plugin to 1.7 in order to activate it again.

I faced a fatal error. I don´t know if it is related to 1.7, 1.6, 1.5 or 1.4.

"It wasn´t possible to activate the plugin because it has generated a fatal error."
Parse error: syntax error, unexpected ':', expecting ';' or '{' in /www/htdocs/pep-rohm.facc.ufrj.br/cms/wp-content/plugins/forms-gutenberg/tagsHandler/tagHandler.php on line 47

**Comment by munirkamal** [comment]
@maryfromlondon 

There may be major code differences and because the plugin didn't have many real active users at that time I didn't care for the deprecation process. And also there are many updates done to the Gutenberg API lately.

I would suggest you to delete it completely and install a fresh version from WP repo. 

let me know if there are still any issues.

Regards,
Munir

**Comment by maryfromlondon** [comment]
Hello. Thank you for the quick response. I admire all the work poured on this plugin.

I have uninstalled the plugin, and I have removed 2 options on the database:

**cwp_gutenberg_forms_general_settings** whose value was default, in portuguese language: {"messages":{"name":{"label":"Name","value":"O nome {{value}} não é válido!"},"email":{"label":"Email","value":"O e-mail {{value}} não é válido!"},"text":{"label":"Text","value":"O texto {{value}} não é válido!"},"message":{"label":"Message","value":"A mensagem {{value}} não é válida!"},"phone":{"label":"Phone","value":"O celular {{value}} não é válido!"},"website":{"label":"Website","value":"O website {{value}} não é válido!"},"number":{"label":"Number","value":"O número {{value}} não está no alcance!"},"file-upload":{"label":"File Upload","value":"O arquivo {{value}} não é válido!"}}}

**widget_gform_widget** whose value was: Array a:1:{s:12:"_multiwidget";i:1;}

Unfortunately, searching the plugin on the wp-admin-plugin´s page, and reinstalling it again brought the fatal error.
I must recognize that the PHP is 5.6.40, and all WP-tables on the database are cleaned from from time to time.

**Comment by marceloaof** [comment]
Hello. On the latest update 1.8.0, the fatal error is still there due to a similar reason, but now the error is originated on a different file:

> Parse error: syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in /www/htdocs/website.com/cms/wp-content/plugins/forms-gutenberg/triggers/email.php on line 447

**Comment by munirkamal** [comment]
@marceloaof 

Are you getting it for updating from an old version only?
