### ISSUE TITLE
Email Block - check to see if e-mail address has been included.

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#19]
In regards to the Email block.
Here it should check to see if the user has filled in an e-mail address.
As someone might just write a bunch of words instead of an e-mail address.

**Comment by munirkamal** [comment]
@paaljoachim 
The basic validation has already been applied. 

![Image 2020-02-16 at 8 03 10 PM](https://user-images.githubusercontent.com/5817882/74607087-67646b80-50f7-11ea-8bb7-8f6b1ab96430.png)

Didn't it work? Or are you suggesting something else?

**Comment by paaljoachim** [comment]
Ahh yes that works!
Closing the issue.
