### ISSUE TITLE
Cleaning up Form blocks

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#20]
I decided to go through the Form blocks that exist at current time.
![Screen Shot 2020-02-16 at 12 19 43](https://user-images.githubusercontent.com/5323259/74603703-afaf6980-50b6-11ea-91fb-d818d4d465a7.png)
![Screen Shot 2020-02-16 at 12 30 47](https://user-images.githubusercontent.com/5323259/74603844-344eb780-50b8-11ea-9e58-6bb85b113794.png)

Name
Form Column
Form Group
Phone
Email
Number
Date Picker
Radio
checkbox NB! Rename to = "Checkbox"
Website
Text
Message
Select
Yes/No NB! Rename to = "Toggle"

Name, Phone, Email, Website are it seems identical to Text.
Remove Name, Phone and Website and have the Text Block first in the list.

Email needs an e-mail validator. I opened an issue for this.

**Reordering the Form Blocks list:**
Text (numbers can not be inserted)
Email (includes an automatic validator of e-mail address in use on frontend.)
Message (multi line box)
Number (letters can not be inserted. Is blank on the frontend.)
Form Group
Form Column
Radio
Checkbox
Select
Toggle

It gives a better generic overview of available blocks. A text field can be used for any one line text area. Message for a multi line area. Number is used for zip codes, telephone numbers etc.

**Comment by munirkamal** [comment]
@paaljoachim 

Well, again this is default Gutenberg behavior for showing the nested blocks. It shows the last used blocks in that list first. Therefore you don't see the list remain in the same order. 🤔

Regarding the different field blocks. Basically I added them separately as they have different input types. You might not have thought about it but an accurate input type behaves differently in different browsers/devices.

For example:
The phone block is an input type "tel" which opens up a numeric keypad in a mobile device.

![Image 2020-02-16 at 8 19 49 PM](https://user-images.githubusercontent.com/5817882/74607303-b4494180-50f9-11ea-8441-056c75f03c43.png)


And may have some non-standard attributes as well, such as `[autocorrect](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel#autocorrect)` and `[mozactionhint](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel#mozactionhint)`. 

And may also have different default validations. You may read more about "tel" input type here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel

So this is why I have this in place now. And in the future, we may add different validation and other features to specific field types.

**Comment by paaljoachim** [comment]
> Well, again this is default Gutenberg behavior for showing the nested blocks. It shows the last used blocks in that list first. Therefore you don't see the list remain in the same order. 

Ahh yes the most used fields do show first. That is right.

> For example:
The phone block is an input type "tel" which opens up a numeric keypad in a mobile device.

Great!


I am thinking these fields who be identical: Text, Name and Website and could perhaps be merged into the Text field.

**Comment by munirkamal** [comment]
I think these fields are fine separately. Different attributes and better to keep it like this. Most forms have it separately as well.
