### ISSUE TITLE
Readjusting Required Text and Error validation text

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#21]
I clicked to require a field, but the user should not need to add a required text if they choose not to. 

Backend with required fields:
![Screen Shot 2020-02-16 at 12 38 58](https://user-images.githubusercontent.com/5323259/74603972-8fcd7500-50b9-11ea-9abb-abe2e9f4a6b2.png)

Frontend: (Required is made so the user needs to fill out a field. It should not automatically show a required text. If one fills in something into the Required text field then that can show or else it would not show.)
![Screen Shot 2020-02-16 at 12 41 27](https://user-images.githubusercontent.com/5323259/74603984-ac69ad00-50b9-11ea-9b5e-934281a176da.png)

This also adds in the Error Validation Text. Default is included so that the user does not have to fill out the Error validation text for all the fields, but fill out one and have it automatically repeated to all other fields as well. Removing the text automatically brings back the placeholder text.

![Error-Validation-Text-Gutenberg-Forms](https://user-images.githubusercontent.com/5323259/74604378-ac6bac00-50bd-11ea-8896-92e2380069a8.jpg)

Or something like this:
![2-Sidebar-error-validation-text-Gutenberg-Forms](https://user-images.githubusercontent.com/5323259/74607078-cb763800-50d5-11ea-9c69-9464fecf887b.jpg)

**Comment by paaljoachim** [comment]
Use case for adjusting the error validation field seen on the frontend when someone does not fill in the required field.

![Screen Shot 2020-02-16 at 13 05 34](https://user-images.githubusercontent.com/5323259/74604310-0d46b480-50bd-11ea-9201-a69949a32bda.png)

For instance I do not want to use the words "Please fill in this field" but want to use something in Norwegian for all the fields that have required toggle on.

I also included the default. Clicking this will automatically use the text I inserted instead of the "Please fill in this field"

**Comment by munirkamal** [comment]
Ok so to make clear here is what needs to be done.

1) Required text if left empty, needs not to display anything on the front-end.
2) The required text added to a field may be saved as the default value to appear on all new fields added, but still changeable.
3) The same applies to the "Validation Error Text" field (for specific field blocks).

Is that correct @paaljoachim ?

**Comment by paaljoachim** [comment]
> Required text if left empty, needs not to display anything on the front-end.

That is correct.

> The required text added to a field may be saved as the default value to appear on all new fields added, but still changeable.

I had not thought of that but yes that is a good idea.

> The same applies to the "Validation Error Text" field (for specific field blocks).

Yes. That is correct.

**Comment by munirkamal** [comment]
Done a little differently than discussed. We have the ability to change defaults on the Form level or field level. Explained here.
https://github.com/munirkamal/gutenberg-forms/issues/16#issuecomment-589058591

**Comment by paaljoachim** [comment]
Btw tooltips are needed. Hover over a ? and get information for each what they do. I made a new issue for tooltips.
