### ISSUE TITLE
Columns inside Group field

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#22]
As I am rebuilding a form I happen to notice this:
Notice the bottom breadcrumbs.

![Screen Shot 2020-02-16 at 13 12 43](https://user-images.githubusercontent.com/5323259/74604418-1421f700-50be-11ea-8208-d30e2fc0c427.png)

Btw I tried dragging the columns block out of the group block but that did not seem to work.

**Comment by munirkamal** [comment]
What exactly the issue is? 

Seems like you have added another form block inside a form block? Is that correct? 

And in regards to dragging the column out, this is again something to be improved in the Gutenberg editor itself. 🤨

**Comment by paaljoachim** [comment]
> Seems like you have added another form block inside a form block? Is that correct?

It seems like it. I do not know how it happened.

Hmm yeah. I tested in regular Gutenberg blocks. I was not able to drag columns out of the Group block.

I will just go ahead and close this issue for now.
