### ISSUE TITLE
Adjusting the Number field

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#24]
There are different ways to use the Number field

(Example from Gravity Forms form)
As a regular number: zip codes, telephone number etc.
<img width="329" alt="Screen Shot 2020-02-16 at 13 28 07" src="https://user-images.githubusercontent.com/5323259/74604637-3157c500-50c0-11ea-907a-1779c2307e1c.png">

(Example from Gravity Forms form)
As a count up/down by 1 or any count.
<img width="260" alt="Screen Shot 2020-02-16 at 13 28 45" src="https://user-images.githubusercontent.com/5323259/74604650-46ccef00-50c0-11ea-9e53-fd5dd77c6b51.png">

(Example from Guteneberg Forms.)
As a range slider (Not sure how this one works..):
![Screen Shot 2020-02-16 at 13 30 35](https://user-images.githubusercontent.com/5323259/74604698-a7f4c280-50c0-11ea-87a3-33b4068d5d66.png)
Perhaps the range slider should have its own field named: Range Slider.

That also means one needs to sometimes show a count up/down, a slider.
But most often as just a regular number field.

**Comment by munirkamal** [comment]
So we may have 3 types simple to the number blocks.

- Default (Regular Number Input)
- Stepper
- Slider

**Comment by ZafarKamal123** [comment]
The number field cannot work like a text field. It may either be a stepper or a slider. For other purpose use text field and define a pattern as per requirement.

Note: Pattern option has been added.

**Comment by paaljoachim** [comment]
Can you please explain with a few more details? Thanks.

I see this in the number Validation Pattern:

![Screen Shot 2020-02-22 at 23 54 27](https://user-images.githubusercontent.com/5323259/75100510-b403e700-55ce-11ea-8a0a-99ccf66b4d3a.png)
