### ISSUE TITLE
Improving the date picker

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#25]
Todays Date picker looks like this:
![Screen Shot 2020-02-16 at 16 10 10](https://user-images.githubusercontent.com/5323259/74607177-d5e50180-50d6-11ea-9200-cddfdad01eaa.png)

Here is the one used in Gravity Forms.
![Screen Shot 2020-02-16 at 16 07 54](https://user-images.githubusercontent.com/5323259/74607179-dc737900-50d6-11ea-9812-36a6558213fd.png)

In Gravity Forms it is easier to in a drop down select year and month. 
The current date picker in Gutenberg Forms it is harder to go back to 30-40 years to for instance birth date, as one would have to click the left arrow button to go one month at a time backward.

**Comment by munirkamal** [comment]
@ZafarKamal123 

Implement a better date & time field. Check this:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

@paaljoachim 

However, this also has the ability to quickly go back in years (see GIF below) but I got some ideas to improve it. Thank you for raising this point.

![Screen Recording 2020-02-16 at 08 47 PM](https://user-images.githubusercontent.com/5817882/74607829-efe60a80-50fd-11ea-87bb-3dadc0a7e6e0.gif)

**Comment by munirkamal** [comment]
I have changed the date picker element and now it works the same way as Gravity forms I guess. You may select the year and month by clicking on them and then change the date.

Here is a rough screencast to show how it works. 
http://youtu.be/zeZMx5Az8q4?hd=1

Additionally, I have also added a formatting option (which seems not working, will get it fixed).

**Comment by paaljoachim** [comment]
That is awesome Munir! A very well thought out feature!!

**Comment by paaljoachim** [comment]
Btw I happen to come across this PR: https://github.com/WordPress/gutenberg/pull/19857
