### ISSUE TITLE
Conflict with Gutenberg plugin

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#270]
I am testing the form to see how easily it can create this form:
https://gaiatravel.no/pamelding/

Test site:
Browser: Brave.
Theme: Twenty Twenty Three (FSE)
WordPress 6.1.1
Active plugins: Gutenberg 15.0.1 and Gutenberg Forms 2.2.9

I duplicated the default Message field. Then worked on getting it smaller. I adjusted the maximum length (characters) and then I dragged the bottom edge up.

Can be seen here:
![Dragging Message field](https://user-images.githubusercontent.com/5323259/214159028-3de4a1ec-d1c1-4b2d-b942-dc219cb088a7.gif)

I did expect to have the drag lines be related to the message field box.

**Comment by paaljoachim** [comment]
Actually clicking the form looks like this:

![Screenshot 2023-01-23 at 23 01 55](https://user-images.githubusercontent.com/5323259/214159815-56df9d32-fd71-432c-933f-e786cdacdad2.jpg)

**Comment by nikolaystrikhar** [comment]
@kktr please check

 I can't replicate it in Safari, so may be browser related.

**Comment by paaljoachim** [comment]
Retesting.
Ahhh with the Gutenberg plugin version Version 15.0.1 deactivated it looks correct. 

![Screenshot 2023-01-27 at 22 55 32](https://user-images.githubusercontent.com/5323259/215210448-34e9ccaf-88e8-421f-8257-2da3f97afab4.jpg)

With the Version 15.0.1 Gutenberg plugin active I see this:
![Screenshot 2023-01-27 at 22 58 01](https://user-images.githubusercontent.com/5323259/215210677-f522edfd-f2dc-4014-bd57-00d46c447bbd.jpg)

EDIT: Same result in the Safari browser.

**Comment by nikolaystrikhar** [comment]
@paaljoachim may I ask why you use this plugin, when it is useful, etc? Just to get better the whole idea behind it.

**Comment by paaljoachim** [comment]
I gave feedback to Gutenberg Forms when it was initially created. As you are now developing the form I became curious of how it now works. I have earlier used Caldera Forms and I am looking around for alternatives. I began testing Gutenberg Forms again, but became a bit stuck when I was not able to create something like this: https://totalhelse.no/pamelding/
(It is actually a newly developed site that still needs more content from the client. The form in use is the depreciated Caldera Forms. It is still available on Github. I zipped up Caldera from another site and then added it to the new site.)

Ping me when the next version is out. Thanks!

**Comment by nikolaystrikhar** [comment]
@paaljoachim I want to be honest, while I truly appreciate you spend your time helping Gutenberg Forms, and I love it too, I would not recomment using it in production. We may have to do breaking changes (I hope not critical). So at the moment it's not really a good plugin to use. It has a huge potential and we fix bugs one by one, but there is a long journey to become at least "normal" to be honest.

I will try to keep in contact with you, I really love your support and I appreciate it!

**Comment by paaljoachim** [comment]
Thanks for the feedback @nikolaystrikhar Nikolay!
We will see what happens. I will continue using Caldera Forms even if it does not exist any longer on the WordPress plugin repo, and see how it goes. See what other forms plugins show up along the way. Have a great weekend!

**Comment by nikolaystrikhar** [comment]
Will be fixed in the new version.
