### ISSUE TITLE
Dragging form fields into Gutenberg column

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#271]
Hi

I am working on creating a two column layout with many rows.
Similar to this Caldera Forms form: https://gaiatravel.no/pamelding/

I added a column and expected to be able to drag and drop form fields into the columns to create the two column layout.
That did not work.

![Drag form blocks into Column](https://user-images.githubusercontent.com/5323259/214160789-332ee1a8-e1b0-4732-b100-c9188f0a4037.gif)

I then looked at the sidebar for a Message field block I had selected to see if there was a method there. I did not find any.
I thought that Gutenberg Form fields would be able to play with the Gutenberg editor default fields.

Twenty Twenty Three - FSE
Gutenberg plugin 15.0.1 and Gutenberg Forms newest version 2.2.9 active.
Brave browser
WP 6.1.1

**Comment by nikolaystrikhar** [comment]
Hey,

I have not tested it yet, but right now Gutenberg Forms has it's own column block. And all field blocks can be inside a form, or inside a GF column/group block. Fields can't be inside a usual column block.

We are thinking about it at the moment.

<img width="318" alt="Screenshot 2023-01-26 at 22 16 01" src="https://user-images.githubusercontent.com/4025589/214952113-af8a532e-efe8-41a0-b8c2-efc1827a72b8.png">

cc @kktr

**Comment by nikolaystrikhar** [comment]
I honestly think I prefer to fix it and I know the way, but I also need to deprecate the old column and group blocks. I’m not really familiar with all the latest Gutenberg features, so learning on the fly, and doing it in the evenings and on weekends does not help haha, but thanks for testing, I really don’t have much time to test, most time I spend trying to rework blocks so it’s easier to support them in the future. A huge work has to be done.
Of course I always want it to do immediately, but life is life🙃

I would not suggest to use the current GF column block, as I’m going to deprecate it. 

The reason it was made this way is it was developed long time ago and the feature you are talking about appeared in the WP 6.0. So authors could not do it, they could operate with parent blocks only. So they had to recreate a column and a group block, which is absolutely weird, but it’s our history, right?😅

**Comment by nikolaystrikhar** [comment]
Will be solved in the next release.

**Comment by paaljoachim** [comment]
Hey Nikolay! 
I run easywebdesigntutorials.com and there are a lot of tutorials that I want to add, but it comes back to inspiration and time. Thanks for sharing!
Nice to see that it will be solved in the next release!
Have a nice weekend!

**Comment by nikolaystrikhar** [comment]
Hey,

Cool website, I bet it helps people :-)

Yeah, it will be solved, but I have no idea when we can expect the next release, it takes a lot of time to rework at least something.
Tutorials would be cool, and I also would like to add tutorials to gutenbergforms.com, but first we need to fix all simple issues like this one.

You too! Thanks for your help!
