### ISSUE TITLE
Go through and add hover tool tips to new settings that need a better explanation

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#30]
Hey

We need some ? (question mark) hover tool tips to the new settings where it mentions editing validation/error/etc messages. As it can be difficult to know what each setting does.

Thanks.

https://youtu.be/LXSV2LiAzRM

(Testing the Master on Friday evening - Looks like the new features will be added to the next Master.)

**Comment by munirkamal** [comment]
Will workout on documentation and help hints for different parts of the form.

**Comment by paaljoachim** [comment]
Because of how you have adjusted the Required and Messages settings in version 1.0.7. There is really no need for hover tips. A general documentation for the plugin is always good to have access to for any user.

**Comment by paaljoachim** [comment]
I will close this issue for now. If needed we can reopen.
