### ISSUE TITLE
Confusing with Required text and Invalid Name Error

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#31]
When turning on a field to become required a red star is seen.

![Screen Shot 2020-02-22 at 18 07 47](https://user-images.githubusercontent.com/5323259/75096267-3f18b900-559e-11ea-81ba-890c0c74aa4e.png)

Required usually means that one has to fill in the field.

Turning on Required in the backend the Required Text box is also seen. It should start out blank.
![Screen Shot 2020-02-22 at 18 10 52](https://user-images.githubusercontent.com/5323259/75096312-c6fec300-559e-11ea-8daa-321caf7ac812.png)

When a user fills out the Required text is should also show up next to the title of the block in the backend. As it shows right away in the backend what Required text is.

---

Then below we have the Messages area.
![Screen Shot 2020-02-22 at 18 13 09](https://user-images.githubusercontent.com/5323259/75100357-d85ec400-55cc-11ea-9516-1c329b59d175.png)

Required Error should be close to the Required toggle. When the required toggle is on the required error "Please fill out this field! will be seen when the user does not fill out a field and clicks the submit button.

Invalid Name Error needs a tooltip hover as mentioned in another issue.

So from my understanding. Here by level of importance and most used.
1. Required Error - Message that will show up when a field is required and not filled in when user clicks the submit button.

2. Required Text - Is an optional text that can be added next to the field title when Required toggle is on. 

3. Invalid Name Error - A specific error message that will show up for an unique field. 
Example user forgets to add a @ to the e-mail address. An unique error message will show up.

O and then we also have the Validation. That is a lot of extra stuff most people might not at all need.

For instance the only thing I would like to see get more focus is the Required error text. The rest can be more hidden away.

**Comment by munirkamal** [comment]
Implemented it in v1.0.7. It now shows you the required text entered in the editor view as well (not when you focused the field though).

Regarding other confusions, I will prepare docs which will make things clear.

**Comment by paaljoachim** [comment]
This is really nicely laid out!

Field Settings.
Required. Activate to turn on Required Text.

Messages area.
Required Error
Invalid Email Error.

This is very nice!
<img width="280" alt="Screen Shot 2020-03-03 at 10 55 48" src="https://user-images.githubusercontent.com/5323259/75764048-94429080-5d3d-11ea-896f-a327125272a6.png">
