### ISSUE TITLE
Looking at Calculations field

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#32]
I am looking at the calculations field.

Added two number fields. Made one can duplicated the first so that I have two number fields.
Then added them into the calculation.
Added a + between the two fields.

![Screen Shot 2020-02-23 at 00 04 16](https://user-images.githubusercontent.com/5323259/75100590-0c87b400-55d0-11ea-9611-4dbfa1aab8b4.png)

This is what it looks like on the frontend:
![Screen Shot 2020-02-23 at 00 05 46](https://user-images.githubusercontent.com/5323259/75100608-4789e780-55d0-11ea-952e-dd4e0b4e6b46.png)

Adding 5 to the first number field.

Total changes to 10. Perhaps it has to do with duplicating the first number field.
![Screen Shot 2020-02-23 at 00 06 23](https://user-images.githubusercontent.com/5323259/75100613-57a1c700-55d0-11ea-9606-6ec25cb728af.png)

Deleting the duplicated number field to add a new.
It made no change.

--

I this time instead of + added a - to see how that goes.
It looks like I am missing something.

Btw there should be a llist right by the title "Available Number Fields:" So users can see what kind of math symbols can be used.

I turned off the Formula Editor and then saw XX instead of a field box.

**Comment by munirkamal** [comment]
@ZafarKamal123 

This surely a Bug. When we duplicate the field it keeps the field ID the same and thus causing this issue. Needs to be fixed.

**Comment by ZafarKamal123** [comment]
Fixed
