### ISSUE TITLE
Testing conditions

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#33]
I am testing the conditions.
Choose one.
Technical
Presale
Everything else

Technical issue
Presale issue
Everything else 

![Screen Shot 2020-02-23 at 00 16 46](https://user-images.githubusercontent.com/5323259/75100726-f549c600-55d1-11ea-9268-de9511b42949.png)

I checked the frontend and noticed no select field or any of the conditional fields. I clicked the Edit page button and the page went blank..

![Screen Shot 2020-02-23 at 00 19 43](https://user-images.githubusercontent.com/5323259/75100740-35a94400-55d2-11ea-982b-468827556fb8.png)

Console error:
blocks.build.js:1 Uncaught (in promise) ReferenceError: condition is not defined
    at blocks.build.js:1
    at l (blocks.build.js:1)
    at Vt (index.js?ver=6a9fab2f09ebe19b3213ec8b79e7bd43:2)
    at Ht (index.js?ver=6a9fab2f09ebe19b3213ec8b79e7bd43:2)
    at index.js?ver=0b142f9d4e15a158117d9ebc862e05c2:49
    at index.js?ver=dffa7711c5b78d1a2a82b9a091c30697:1
    at Dr (index.js?ver=6a9fab2f09ebe19b3213ec8b79e7bd43:2)
    at zr (index.js?ver=6a9fab2f09ebe19b3213ec8b79e7bd43:2)
    at Array.map (<anonymous>)
    at zr (index.js?ver=6a9fab2f09ebe19b3213ec8b79e7bd43:2)

It continued showing a blank page.

I had to enter the backend into another page. Going back to the page I had the form in did not work.

Btw the conditions look nice and it is clear how it works. Nicely done!

**Comment by munirkamal** [comment]
@paaljoachim Could you please re-test it with version 1.0.7 and let me know.

**Comment by paaljoachim** [comment]
The above error has gone away.
Associated issue: https://github.com/munirkamal/gutenberg-forms/issues/41

Closing this issue.
