### ISSUE TITLE
Advanced calculations field - The Calculator -

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#34]
With Caldera Forms I have built this calculator used here:
https://celias.no/

![Screen Shot 2020-02-25 at 09 58 12](https://user-images.githubusercontent.com/5323259/75231214-5d0c3680-57b5-11ea-9b60-3d5682020b98.png)

3 tabs on the top Dugnadskort (cards) - Gaveposer (gift bags) - Julepakke (Christmas package)

First slider.
Amount of people attending taking part 22

Second slider.
Amount of products 10

Third slider.
Price kr 250

Some text.
Our suggested sales price kr 250

Some text
Calculated income total: kr 22,000

**Backend**
Header
<img width="1111" alt="Screen Shot 2020-02-25 at 10 04 04" src="https://user-images.githubusercontent.com/5323259/75231873-82e60b00-57b6-11ea-9c8c-22065ad96fc9.png">

Toggle Switch:
<img width="1103" alt="Screen Shot 2020-02-25 at 10 10 21" src="https://user-images.githubusercontent.com/5323259/75232216-21726c00-57b7-11ea-9147-aead0b5fb4cf.png">

Range Slider:
<img width="1129" alt="Screen Shot 2020-02-25 at 10 05 11" src="https://user-images.githubusercontent.com/5323259/75231920-9b562580-57b6-11ea-837d-9810ccf1c83b.png">

Range Slider:
<img width="1124" alt="Screen Shot 2020-02-25 at 10 05 39" src="https://user-images.githubusercontent.com/5323259/75231952-a90bab00-57b6-11ea-9cab-1dcaf9403016.png">

Calculations:
<img width="1123" alt="Screen Shot 2020-02-25 at 10 06 02" src="https://user-images.githubusercontent.com/5323259/75231976-b45ed680-57b6-11ea-9a2c-95f494f84ee3.png">

I can also include an export of the form.
<img width="776" alt="Screen Shot 2020-02-25 at 10 09 07" src="https://user-images.githubusercontent.com/5323259/75232085-e1ab8480-57b6-11ea-840c-6cc4b1792f89.png">

**Comment by munirkamal** [comment]
@paaljoachim 
You may create the same in Gutenberg Forms already. Except that in the free version we have caluclations enabled only for number field type. So the only thing missing will be the top button group.

The export of the form is also possible already like any other Gutenberg Block. Save it as a reusable block and export as json.

**Comment by paaljoachim** [comment]
Yeah. I did some testing and was able to make something similar using Gutenberg Forms. 
That means we also have a good foundation in place to build on.

**Comment by munirkamal** [comment]
Closing it as explained it is already possible. 
And also the number field improved in v1.0.7. 
And for the button group, there is another issue to create a style for radio & checkboxes. #35
