### ISSUE TITLE
Improving the Radio Block and Checkbox Block.

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#35]
**NB! The below is showing for a Toggle but that is a mistake. It should be for radio buttons. It makes radio buttons and also possibly checkboxes nicer.**

I see the basic toggle in place.

Frontend:
(3 toggles beside each other.)
![Screen Shot 2020-02-26 at 09 52 50](https://user-images.githubusercontent.com/5323259/75328157-d66f5c00-587d-11ea-98af-d977a9004e00.png)

Trying to do the same thing as here:
<img width="426" alt="Screen Shot 2020-02-26 at 09 53 36" src="https://user-images.githubusercontent.com/5323259/75328210-f010a380-587d-11ea-899c-e4f066a14372.png">

-------

Switch out the X Yes / No icon with a nicer toggle image. Example here: https://www.ecosia.org/images/?q=toggles%20images#id=0FB992EB9E50C470EC976666CF3335ADA7834432

Improve the look of the default toggle. Have an option to have one or multiple toggles beside each other or below each other. Have text beside, above or inside a toggle.

For instance the Select Block has the feature to add multiple items to a drop down. The Toggle could have a similar feature to add multiple items to a toggle. The calculator is a nice way of showing multiple toggles.

**Comment by munirkamal** [comment]
Not sure if I understand this properly.

A toggle is technically a checkbox styled with CSS to display as a toggle button.

What is the use of having images with toggle like we have for CheckBoxes or Radio fields?

Also, regarding styling the toggle button. I do have plans to add different styles for each form field, but,  later. However, anyone can already register a custom style for any field as similar to any Gutenberg block.
https://developer.wordpress.org/block-editor/developers/filters/block-filters/#block-style-variations

Also, in your example those Buttons are actually not toggle but Radio options displayed as buttons. I may have this as a style for the radio option.

**Comment by paaljoachim** [comment]
Ahh yes you are right!

Ahh yes a toggle is a Yes/No - On/Off switch. 
I do believe toggles are used wrong in Caldera Forms. As these should be radio buttons instead.

I will need to edit the title and some of the original text in the issue.

**Comment by munirkamal** [comment]
Self Note:

Simply create a style for radio & checkbox fields to look like buttons.
