### ISSUE TITLE
Improving the Number (Range Slider) Block

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#36]
Again I am looking at Caldera Forms.
<img width="382" alt="Screen Shot 2020-02-26 at 10 02 08" src="https://user-images.githubusercontent.com/5323259/75328931-1125c400-587f-11ea-8309-ebad77973967.png">

Backend Caldera Forms Range Slider Block:
<img width="1366" alt="Screen Shot 2020-02-26 at 10 03 25" src="https://user-images.githubusercontent.com/5323259/75329124-682b9900-587f-11ea-9ffb-59c6ed41cb55.png">
<img width="370" alt="Screen Shot 2020-02-26 at 10 04 02" src="https://user-images.githubusercontent.com/5323259/75329136-6c57b680-587f-11ea-8741-1cd971046a06.png">

Features to add:
Default/starting value.
Show value (a value is seen beside the slider)
Prefix
Suffix

Existing Range Slider frontend:
![Screen Shot 2020-02-26 at 10 07 04](https://user-images.githubusercontent.com/5323259/75329402-d83a1f00-587f-11ea-9850-27350f838a36.png)

**Comment by munirkamal** [comment]
There are already some improvements added to the number block. If you pull the latest GitHub repo you may notice the range slider updates. 😇

Prefix/Suffix is something I am considering to add on multiple field types (where needed).

**Comment by munirkamal** [comment]
Closing this as the number field is improved already in version 1.0.7. And for the suffix/prefix I have created another issue.
