### ISSUE TITLE
Improving Calculations Block

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#37]
I clicked the Add Field Data.
![Screen Shot 2020-02-26 at 10 18 35](https://user-images.githubusercontent.com/5323259/75330551-90b49280-5881-11ea-8802-7a8db8d77185.png)

There are some missing titles in the popup.
It would also be helpful to see the Prefix or Postfix directly in the Gutenberg backend layout.
Perhaps above the "Available Number Fields:" words. Showing what the line would look like on the frontend before going to the frontend.

**Comment by munirkamal** [comment]
The preview is already there. You just need to switch the formula editor.
![Screen Recording 2020-02-26 at 02 32 PM](https://user-images.githubusercontent.com/5817882/75331663-ebabb100-58a4-11ea-8ba8-70704d162831.gif)


Regarding the empty field labels, this looks like you have some fields without labels? Is it like that?

**Comment by paaljoachim** [comment]
Ahh thanks! Good to see that it can be previewed in the backend.

I believe that are the three toggles I mistakenly used.

**Comment by paaljoachim** [comment]
@munirkamal 

Awesome this works nicely!
<img width="690" alt="Screen Shot 2020-03-07 at 17 51 35" src="https://user-images.githubusercontent.com/5323259/76147417-52e31580-609c-11ea-9154-720028460094.png">

The only thing I feel missing is the starter value field in the sidebar settings. (Yes one can also add it directly in the layout field but it feels less presis.)
