### ISSUE TITLE
Testing out conditions - hides fields on frontend.

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#41]
I made this form:

<img width="786" alt="Screen Shot 2020-03-03 at 09 55 06" src="https://user-images.githubusercontent.com/5323259/75759312-a0c2eb00-5d35-11ea-811a-ce9850d5368c.png">

Name, Email, Choose One, and then What kind of support do you need?
I turned on conditions first in the Choose one and noticed that was the wrong area. Then turned conditions off again. Then turned on conditions in the What kind of support do you need? message box.

<img width="1053" alt="Screen Shot 2020-03-03 at 10 01 25" src="https://user-images.githubusercontent.com/5323259/75759628-2fd00300-5d36-11ea-9c06-221db7c963d9.png">

I was about to take a screenshot of the frontend to show the checkboxes not seen but then they suddenly showed up again.

I added another checkbox field:
<img width="969" alt="Screen Shot 2020-03-03 at 10 07 05" src="https://user-images.githubusercontent.com/5323259/75760011-c7355600-5d36-11ea-893d-e781838d9196.png">

Activated Conditions: Show if Choose One - Is Equal To - Support.

Checked the frontend. Everything is gone.
<img width="861" alt="Screen Shot 2020-03-03 at 10 07 44" src="https://user-images.githubusercontent.com/5323259/75760039-dc11e980-5d36-11ea-9eaf-888dddbc9ad7.png">

There are no developer console errors. I had to go back and turn conditions on and off again.
There is somekind of bug I am not able to locate at present.

I am using Desktop Server in Chrome on my Mac.

**Comment by paaljoachim** [comment]
In wp-config.php I turned on 

define('WP_DEBUG', true);
define( 'WP_DEBUG_LOG', true );

I also installed the plugins:
Error Log Monitor https://wordpress.org/plugins/error-log-monitor/ and
Health Check & Troubleshooting https://wordpress.org/plugins/health-check/

Noticed this show up in the log files:
{\rtf1\ansi\ansicpg1252\cocoartf1561\cocoasubrtf610
{\fonttbl}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww16200\viewh13200\viewkind0
}

I clicked to Trouble Shoot with Health Check & Troubleshooting plugin. Saw this in the frontend:
<img width="890" alt="Screen Shot 2020-03-03 at 10 29 15" src="https://user-images.githubusercontent.com/5323259/75761731-da95f080-5d39-11ea-9f04-e4029ddd7019.png">

Disabled Troubleshooting Mode.

<img width="760" alt="Screen Shot 2020-03-03 at 10 31 30" src="https://user-images.githubusercontent.com/5323259/75761914-2c3e7b00-5d3a-11ea-91f3-6b24394b6920.png">

**Comment by ZafarKamal123** [comment]
Fixed!

**Comment by paaljoachim** [comment]
Hey @ZafarKamal123 

I am testing this again now.
I have the 4 radio buttons. Then made a message box for Support.
Selected it. Turned on Use Condition. Show if Choose One is Equal to Support. Saved the Draft and checked the frontend. The Support message box did not show. Went back to the backend and noticed that the Use Condition had reset itself. I again adjusted the condition.

<img width="1036" alt="Screen Shot 2020-03-07 at 17 36 00" src="https://user-images.githubusercontent.com/5323259/76147203-229a7780-609a-11ea-86b6-8d001f116552.png">

Then I refreshed the browser and noticed that again it has reset itself.
<img width="1034" alt="Screen Shot 2020-03-07 at 17 37 06" src="https://user-images.githubusercontent.com/5323259/76147226-4eb5f880-609a-11ea-9ce4-5e81371af096.png">

**Comment by macemmek** [comment]
Hi @ZafarKamal123,

I have a problem, because the conditions do not work for me at all...

The conditional field is not displayed when condition is set but when I pick radio or select option that should satisfy the condition on the front end, nothing happens.

**Comment by munirkamal** [comment]
@macemmek & @paaljoachim 

I am reopening this issue and will look into it.

Thanks

**Comment by macemmek** [comment]
Oh... I've reopened edit form again and I got white screen.

The console says about:

Unhandled Promise Rejection: ReferenceError: Can't find variable: condition
dispatchException — wp-polyfill.js:6993

Something got messed...

**Comment by paaljoachim** [comment]
I have tested and made a similar form as I initially posted about.
Radio options for: Presale - Technical - Support- Everything else.
The first form opened in this link: https://mai.dev.cc/cwp_gf_forms/a-title/ (A not found page)

I then recreated it again. This time it worked.
I am only focusing on conditions and how these are seen on the frontend.

**Comment by ZafarKamal123** [comment]
Hi @paaljoachim ,@macemmek 

I've tried to create the exact form made in this **issue**.

![screenshot-localhost_8080-2020 05 18-14_06_36](https://user-images.githubusercontent.com/48084051/82195045-31f73600-9911-11ea-8835-9cf73e5923f7.png)

I enabled conditional logic on the **Priority Checkboxes**.

![screenshot-localhost_8080-2020 05 18-14_10_10](https://user-images.githubusercontent.com/48084051/82195160-5e12b700-9911-11ea-979d-2164c5f917c1.png)

And for me, I was unable to replicate this issue. 

![screenshot-localhost_8080-2020 05 18-14_07_15](https://user-images.githubusercontent.com/48084051/82195237-784c9500-9911-11ea-8fe3-40cb95503f70.png)

The **Conditional Logic** works as expected on the frontend. I've also tried refreshing the page.
Please retest after the upcoming update and let me know!

Thanks 👍

**Comment by paaljoachim** [comment]
Will do!

**Comment by macemmek** [comment]
Hi @ZafarKamal123,

did you try with a condition based on select option value?

It crashed my form edit screen. Also in 1.4.0 from Github.

![screenshot 2020-05-22 o 16 03 00](https://user-images.githubusercontent.com/513306/82676095-1c05b000-9c46-11ea-8883-272c2d31bca4.png)
