### ISSUE TITLE
Range Slider preview shows max 2 digits. Truncates anything else over 2 digits.

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#42]
Anything over 2 digits/numbers will not show in number box preview.

Backend (works fine with only 2 digits but adding 3 digits it will only show 2.)
<img width="679" alt="Screen Shot 2020-03-03 at 10 44 51" src="https://user-images.githubusercontent.com/5323259/75763134-0f0aac00-5d3c-11ea-8e5d-e59942ff38f3.png">

Frontend:
<img width="654" alt="Screen Shot 2020-03-03 at 10 45 44" src="https://user-images.githubusercontent.com/5323259/75763177-28abf380-5d3c-11ea-9578-48810c8b1ea2.png">

Make the backend and frontend Range Slider preview number box bigger. So that it can show more then 2 digit numbers.

**Comment by ZafarKamal123** [comment]
Fixed

**Comment by paaljoachim** [comment]
Hey @ZafarKamal123 

Nice job!

I did some additional testing.
If the Range Max is 10000 (more then 1000) then one will still see 1000 in the Range Max setting. These fields need to be able to show more then 9999.
