### ISSUE TITLE
Date picker: Red color seen 

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#43]
I am seeing a red color in the dates in the date picker:

Backend:
<img width="666" alt="Screen Shot 2020-03-03 at 11 00 15" src="https://user-images.githubusercontent.com/5323259/75764486-382c3c00-5d3e-11ea-8de8-24ab23e01e5a.png">

Frontend:
<img width="664" alt="Screen Shot 2020-03-03 at 11 00 50" src="https://user-images.githubusercontent.com/5323259/75764519-42e6d100-5d3e-11ea-827d-ed9df49004cf.png">

**Comment by ZafarKamal123** [comment]
This looks like the issue with the twenty twenty theme which is applying their accent color to all the links and buttons.

**Comment by paaljoachim** [comment]
Ahhh. Gotcha. I will check later on with another theme.
