### ISSUE TITLE
Range Slider sidebar settings

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#44]
I am looking at the Range Slider settings.

Number field. Range Slider not selected.
<img width="974" alt="Screen Shot 2020-03-03 at 11 04 28" src="https://user-images.githubusercontent.com/5323259/75764868-d1f3e900-5d3e-11ea-994c-54bcd1530fc3.png">

We are still seeing a Field Settings and Range Settings associated with the Range Slider.

Adjust:
Move all settings associated with the Range Slider into the Range Setting. Keeping all Range Slider settings in one area.
Hide Range Settings when Range Slider is NOT selected. 
When Range Slider is turned on then show Range Settings.

Field Settings - use for all Number settings (Range slider and regular Number)
Range Settings - Only For Range Slider.

**Comment by ZafarKamal123** [comment]
Fixed! 👍
