### ISSUE TITLE
Style the border around the group block

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#45]
The group block is working a lot better and looks better.

One thing I am seeing is a border around the group block.

Backend:
<img width="960" alt="Screen Shot 2020-03-03 at 11 15 39" src="https://user-images.githubusercontent.com/5323259/75765795-5abf5480-5d40-11ea-8c3f-17db6cd05c16.png">

Frontend:
<img width="711" alt="Screen Shot 2020-03-03 at 11 16 19" src="https://user-images.githubusercontent.com/5323259/75765844-6f035180-5d40-11ea-9f97-c2bd75774289.png">

Perhaps a styling option for border?
Color
Size
Radius

**Comment by simonhammes** [comment]
Hi :)
Can I give this a try?

**Comment by munirkamal** [comment]
> Hi :)
> Can I give this a try?

Of course 😇
Create separate issues for the bugs or suggestions you may have. You may also contribute to development via PR. 🙌
