### ISSUE TITLE
Sending emails doesn't work in nested blocks.

### ISSUE THREAD

**Issue by jwahdatehagh** [munirkamal/gutenberg-forms#47]
When nesting a form within another gutenberg block (e.g. core/group or core/columns > core/column), the Email class can't find the form data and thus can't send emails.

**Comment by jwahdatehagh** [comment]
Code quality-wise i think parsing the template has no place in the `Email` class. There should be a separate Blockparser class for example, which could be even extracted as a separate composer package and then used within this package. If you'd like i could contribute that as well...

**Comment by munirkamal** [comment]
> Code quality-wise i think parsing the template has no place in the `Email` class. There should be a separate Blockparser class for example, which could be even extracted as a separate composer package and then used within this package. If you'd like i could contribute that as well...

If you can, that would be super helpful.
