### ISSUE TITLE
Error when editing nested form fields

### ISSUE THREAD

**Issue by jwahdatehagh** [munirkamal/gutenberg-forms#48]
Trying to edit a form field winin a nested form throws a JS error and breaks the gutenberg editor (also see #47).

This doesn't happen when editing a form field within a form that was added as a root component to the gutenberg blocks.

**Comment by ZafarKamal123** [comment]
Thanks for noticing, This issue is fixed now 👍

**Comment by jwahdatehagh** [comment]
Awesome 👍
