### ISSUE TITLE
Submit button should have its own sidebar settings - split away from the full form.

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#5]
This is what I am trying to say...

Today one clicks each field and one sees the options in the sidebar.
Clicking the Submit button activates the full form sidebar options.

Submit button should have its own sidebar options. Clicking outside the Submit button into the empty space around it should then select the form options.

Today General for submit button contains:
Button Alignment
Button Background Color
Button Color. NB! Button Color should be renamed to **Button Text Color**

Move this into a separate Submit (Buttons block) options.

-----------

General form options sidebar settings.
Background color.
Background image. (Perhaps similar controls as the Cover Block).
Text color for all fields.
Then the various other sidebar settings such as Notification, Confirmation etc.

**Comment by munirkamal** [comment]
I need to think about how best to handle this. 

If I make the submit button a separate block like other input fields, what if a user forget to add the submit block? 

Upon researching in Gutenberg API, I couldn't see a way to check and force a nested block to be used at least once per parent block. We do have a way to limit a block to be used (no. of times) on a per post basis, but not per parent block basis. 

What I can do is simply show a notice in the editor if no "Submit Button" block is added to soft remind the user to add one.

What do you think?

Another issue I see will be with the captcha position/display. As it is not a block as well and currently it is display just above the button block. But when we make the button block to be added anywhere, where should we display captcha?

@paaljoachim Your thoughts?

**Comment by paaljoachim** [comment]
Hey Munir

I think this is a good idea:

> What I can do is simply show a notice in the editor if no "Submit Button" block is added to soft remind the user to add one.

**Comment by munirkamal** [comment]
Added a "Button Block" which can be added anywhere in the form and has different action types. Currently, submit & rest actions have been added, there may be more later.

The default submit button is still there, however, it can be disabled (option added).

This is useful when a user needs to display the submit button elsewhere or have a specific design for the form layout.

Note: The default button styling options still there as it is part of the form block. I may, however, organize those options better while adding "Theme/Design" options for the form.
