### ISSUE TITLE
Sidebar settings alignment and type need improvement

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#59]
Hey

Testing newest version 1.0.9.
With Gutenberg version 7.7.1.
Using Twenty Twenty.
In Chrome.

I am doing some testing and came across this:

![Screen Shot 2020-03-21 at 21 02 11](https://user-images.githubusercontent.com/5323259/77235574-417b2c80-6bb7-11ea-9e60-ff4307729f0e.png)

The Button Alignment and the Confirmation Type options need to be adjusted.

**Comment by ZafarKamal123** [comment]
This seems to be an issue with the latest Gutenberg Plugin? 🤔

**Comment by paaljoachim** [comment]
It is.

Here is an example with using Gutenberg version 7.6.

![Screen Shot 2020-03-21 at 21 19 16](https://user-images.githubusercontent.com/5323259/77235862-b7809300-6bb9-11ea-9d97-2e6af2795075.png)

It is pretty tight.

**Comment by ZafarKamal123** [comment]
Yup, It is pretty tight, I will fix it 👍
