### ISSUE TITLE
How will entries be handled?

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#6]
At the moment we can not view entries in the WordPress backend.
I am curious about thoughts on how this should be handled.
Thanks.

**Comment by munirkamal** [comment]
This is something I need to explore how best to implement it.

What is the purpose of saving those entries in the WP Database exactly? Wouldn't people opt to port those entries to an external CRM or Mailing service? 

Is there another use-case for saving entries in the WordPress database?  We also need to note that this adds up a burden on your site's database and raises some security concerns as well.

**Comment by paaljoachim** [comment]
> What is the purpose of saving those entries in the WP Database exactly? 

> Is there another use-case for saving entries in the WordPress database? 

E-mail entries are then easier available in the backend. The user can just login and go to entries to see them located on the same site they have the form. But having some kind of simple info on better suggestions could also work out alright...


> Wouldn't people opt to port those entries to an external CRM or Mailing service?

Another option could be to suggest some (free) services and how to port these entries into it. It could be a documentation page etc. Not sure at this time.

But yeah this is something to think about.
The question: What is an easy way for the user to gain access to entries?
In the WP backend. In a simple to use free/premium CRM or Mailing service. Or another option....

**Comment by simonhammes** [comment]
As a first step, I would save each form submission as a CPT and create an admin page in the Backend where the admin can view the successful submissions in a table, preferably with a csv export.

**Comment by munirkamal** [comment]
> As a first step, I would save each form submission as a CPT and create an admin page in the Backend where the admin can view the successful submissions in a table, preferably with a CSV export.

Yeah, this is something we need to explore the best way to do it in consideration with Gutenberg. I was also thinking to make it an add-on as it also involves some security risks? 

@simonhammes What are your thoughts?

**Comment by simonhammes** [comment]
> I was also thinking to make it an add-on as it also involves some security risks?

Maybe the user should decide whether the entries will be added to the database or not.
I only reckon that this is an important feature which many people want in a forms plugin.

@munirkamal Which security risks do you mean? SQL injection? Spam?

**Comment by munirkamal** [comment]
Yeah, it's up to the user obviously to decide it. 

And yes I was referring to the SQL injection & spam. However we have already implemented necessary security measures, but you know there is more risk involved in recording entries vs sending the email. 

But sure this is the most important feature as you said. So what is the best way to implement it in your opinion?

**Comment by simonhammes** [comment]
> However we have already implemented necessary security measures, but you know there is more risk involved in recording entries vs sending the email.

That's right.

> But sure this is the most important feature as you said. So what is the best way to implement it in your opinion?

I did some research and it seems like a custom table is the best option. I will look into it.

**Comment by munirkamal** [comment]
CF7 is doing it the same I was thinking. They have a separate plugin for Entry management. https://wordpress.org/plugins/flamingo/

**Comment by simonhammes** [comment]
Alright, I've made some progress using a CPT to save the entries.
Using a custom table would be more performant (but harder to implement, of course). Maybe this is something for the future.

But I have two minor open questions that I would like to discuss:
1. What should the PHP namespace be? I'm not a fan of prefixing every function etc so I've started writing a class for the AdminPage etc.
2. Which capability is needed to view the submissions in the admin area?

**Comment by munirkamal** [comment]
Hey @simonhammes 

First of all, Thank you so much for the contributions you are doing. Much appreciated.

For the entries, yeah let's keep it simple for now. Regarding your questions, here is what I think.

1) Yeah if you are using class then no need to prefix every function obviously. When you do need to prefix, I would suggest "cwp_gf".

2) I've just tested the Flamingo plugin and they are only allowing Admin Role to view the entries. I was thinking about the minimum "Editor" role? What do you think?

Btw, for this Entry Management, I would highly suggest you look at how Flamingo does this. This plugin is by CF7 and seems to do this job pretty nice for years.
https://wordpress.org/plugins/flamingo/

Thanks

**Comment by simonhammes** [comment]
> First of all, Thank you so much for the contributions you are doing. Much appreciated.

It's a pleasure :wink: 

> 1. Yeah if you are using class then no need to prefix every function obviously. When you do need to prefix, I would suggest "cwp_gf".

Okay. And for the namespace? I've selected CWP\GutenbergForms for now, but of course I am willing to change that any time

> 2. I've just tested the Flamingo plugin and they are only allowing Admin Role to view the entries. I was thinking about the minimum "Editor" role? What do you think?

I agree on you. Editors should be able to view the submissions since they are also able to create the forms themselves. The admin role should only be required to modify or delete submissions (that's a possible feature for the future).

> Btw, for this Entry Management, I would highly suggest you look at how Flamingo does this. This plugin is by CF7 and seems to do this job pretty nice for years.
> https://wordpress.org/plugins/flamingo/

Thank you. I've just had a look at it and I don't understand the difference between "Inbound" and "Outbound". I've also installed the CF7 main plugin and entered some data into an example form and they show up under "inbound messages". What's "outbound messages" there for?
Unfortunately there are no comments at all :/

**Comment by munirkamal** [comment]
> Okay. And for the namespace? I've selected CWP\GutenbergForms for now, but of course I am willing to change that any time

Namespace Looks good to me.

> I agree on you. Editors should be able to view the submissions since they are also able to create the forms themselves. The admin role should only be required to modify or delete submissions (that's a possible feature for the future).

Sounds good.

> Thank you. I've just had a look at it and I don't understand the difference between "Inbound" and "Outbound". I've also installed the CF7 main plugin and entered some data into an example form and they show up under "inbound messages". What's "outbound messages" there for?
Unfortunately there are no comments at all :/

Where exactly you see Outbound Messages? I only see Address Book & Inbound Messages sections.
https://share.getcloudapp.com/ApurW8Xy

**Comment by simonhammes** [comment]
@munirkamal 
> Where exactly you see Outbound Messages? I only see Address Book & Inbound Messages sections.
> https://share.getcloudapp.com/ApurW8Xy

Ah I'm sorry. I forgot to say that I'm talking about the plugin code.
Link to Github Repo: https://github.com/takayukister/flamingo (for example in the includes folder)

**Comment by munirkamal** [comment]
@simonhammes 

I see. I am also not sure about that. Anyway, we just need to record entries for now. More can be improved with it later. The more simple we can keep it, for now, the easier it will be to improve later. 😇

**Comment by munirkamal** [comment]
Finally, we've done this. Almost there just some admin column stuff left to finalize and a couple of other stuff. 

@simonhammes I know you started working on it, but I needed to add this feature asap so we did it. But, if you got time and review it and pass your suggestions to improve it, we may apply that.

It is currently in a separate branch.
https://github.com/munirkamal/gutenberg-forms/tree/form-entries

Hopefully will finish it off by tomorrow.

**Comment by simonhammes** [comment]
> @simonhammes I know you started working on it, but I needed to add this feature asap so we did it. But, if you got time and review it and pass your suggestions to improve it, we may apply that.

It's all good :) Maybe I will have the time to take a look at it

**Comment by ZafarKamal123** [comment]
This feature has been added in the latest commit including the **FORM POST TYPE**!
