### ISSUE TITLE
Checkbox and accept terms link

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#60]
Hey

A typical case is having a checkbox/radio and some words saying accept terms. One might want to have a link to the terms page.

Checkbox
![Screen Shot 2020-03-21 at 21 04 06](https://user-images.githubusercontent.com/5323259/77235640-00374c80-6bb8-11ea-8871-88a7f412aced.png)

Radio
![Screen Shot 2020-03-21 at 21 11 25](https://user-images.githubusercontent.com/5323259/77235734-97040900-6bb8-11ea-8216-3c06da3dc839.png)

What about having the paragraph block text field area a nested of the checkbox/radio if possible.
Or adding some styling to the text field area. Bold/Italic/underline and link. That way one can add some text to the checkbox area and select a word to use to link to the terms page.

**Comment by simonhammes** [comment]
> What about having the paragraph block text field area a nested of the checkbox/radio if possible.  

That sounds rather difficult (or even impossible?) to me since the paragraph block would need to be inline.

> Or adding some styling to the text field area.   

I could try adding a setting (in the sidebar) to format the text

**Comment by paaljoachim** [comment]
I went ahead and asked in the #core-editor slack channel.

I am thinking that it might be possible to add some regular styling buttons inline + link. 
(Probably then skip the paragraph block.)
Or a setting in the sidebar.

**Comment by ZafarKamal123** [comment]
Adding some setting for the text formatting might be easy rather than having a paragraph block (Rich Text Formatting).

**Comment by paaljoachim** [comment]
Hopefully the text formatting can be right above the text field. It is nice to have it close by where it is needed.

**Comment by munirkamal** [comment]
Btw,

You may still add a default paragraph block below that checkbox which may link to the Terms & Conditions page, etc. And the checkbox simply says "Accept Terms" (something ) without any link as the link can be added bellow it in a paragraph block. 

@paaljoachim 
How's that?

**Comment by paaljoachim** [comment]
Ahhh of course. That is the easiest way to do these things. I might even just close this issue.
Should I close it? Or is there anything here that should be moved forward?

**Comment by munirkamal** [comment]
I think it can be closed. As I want to keep things simpler and Gutenberg way as much possible, rather than adding things to the plugin which can be handle already. So I am closing it.
