### ISSUE TITLE
Include file upload field

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#61]
Include a basic file upload field.

**Comment by munirkamal** [comment]
This is something I keep for future as there are more things to handle before this.

**Comment by munirkamal** [comment]
@paaljoachim 

This has been added now. Merged in the master branch for testing.

There is a File Field/Block added with option to filter the file types.

**Comment by paaljoachim** [comment]
I just did a test and it works nicely!
I removed pdf from the list and was not able to select a pdf for upload. Nice.

**Comment by paaljoachim** [comment]
Btw in the backend clicking the "Choose File" open the dialog box to choose the file. In the backend this should be a non working button.

**Comment by paaljoachim** [comment]
Testing....

![Screen Shot 2020-03-27 at 15 02 25](https://user-images.githubusercontent.com/5323259/77763845-fd1ae100-703b-11ea-816d-99d0ffce0b01.png)

I have tested with including a png screenshot and a Word Doc file and that worked nicely.

Closing the issue.
