### ISSUE TITLE
Multistep/multipage field block

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#65]
Here is a suggestion for a multistep/multipage block to the regular form.
It flows better to just have a block for it. One does not separate it form the regular form.

This is in relation to:
https://github.com/munirkamal/gutenberg-forms/issues/64

**Comment by ZafarKamal123** [comment]
If we just create a Multistep Block instead of the Type in the main form block, User can actually take two blocks, And can also take fields outside the multistep block. And imo that's something difficult to handle?

**Comment by paaljoachim** [comment]
Ahh there is already a Forms step block.

![Screen Shot 2020-03-23 at 20 01 57](https://user-images.githubusercontent.com/5323259/77353380-29371900-6d41-11ea-822d-c28dac1691cc.png)

The Forms step block can instead be renamed to Multistep Block.

The user should not be able to add  anything between end and start of a Multistep Block.

Todays Forms step block make me think of a group block. I do not know what the difference is right now.

![Screen Shot 2020-03-23 at 20 06 29](https://user-images.githubusercontent.com/5323259/77353725-cc882e00-6d41-11ea-8ed9-7ac10be7e691.png)

**Comment by paaljoachim** [comment]
Btw the multistep block should just have a beginning (no end). It ends at the next multistep beginning block.

**Comment by paaljoachim** [comment]
I believe this issue can be closed.
