### ISSUE TITLE
Group or Column block inside Gutenberg Forms

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#7]
I just added a group block and changed the background color to red.
Then went to add Gutenberg form fields to the Group block.
<img width="874" alt="Screen Shot 2020-02-13 at 17 14 40" src="https://user-images.githubusercontent.com/5323259/74455906-54973000-4e86-11ea-8959-c3a807b54ca6.png">

I could not see any Gutenberg Form field category in Group or Columns (blocks added from outside the Gutenberg Form Field.)

Mixing blocks from outside the Gutenberg Form Field that can be nested will hide the Gutenberg Form field category.

------

Btw
Gutenberg Forms blocks.
<img width="430" alt="Screen Shot 2020-02-13 at 17 35 31" src="https://user-images.githubusercontent.com/5323259/74456514-41d12b00-4e87-11ea-932c-5f6725f8b963.png">

Does not have an accordion arrow beside it (so we can close it) as the standard Gutenberg Block areas:
<img width="546" alt="Screen Shot 2020-02-13 at 17 36 20" src="https://user-images.githubusercontent.com/5323259/74456600-5e6d6300-4e87-11ea-8a65-a50ed99e9ddf.png">

**Comment by munirkamal** [comment]
> Does not have an accordion arrow beside it (so we can close it) as the standard Gutenberg Block areas:

This is Gutenberg's default behavior for all child blocks. 

Will allow Group block to have form field blocks.

**Comment by paaljoachim** [comment]
> This is Gutenberg's default behavior for all child blocks.

I think this default behavior should change. I know every little of how the development is going of nested blocks and will need to look into this.

**Comment by ZafarKamal123** [comment]
Added a form group block in version 1.0.5
