### ISSUE TITLE
Improve Button Block

### ISSUE THREAD

**Issue by munirkamal** [munirkamal/gutenberg-forms#70]
As per feedback from @paaljoachim on issue #64 

Add option for Border setting. Make it have similar options as the default Gutenberg button block has.

Also for the background color try to add the gradient option as it is now available as a component.

**Note:** The background gradient option needs to be added to every background color options we have in the form.

**Comment by paaljoachim** [comment]
To give an overview of what it looks like right now.

![Screen Shot 2020-03-25 at 14 47 35](https://user-images.githubusercontent.com/5323259/77544108-e1330600-6ea8-11ea-8d7c-5a92d51db9df.png)


Future adjustments to the buttons block:
https://github.com/WordPress/gutenberg/issues/20967

**Comment by simonhammes** [comment]
> Add option for Border setting. 

What do you mean by that? 

> Also for the background color try to add the gradient option as it is now available as a component.

The gradient picker is still experimental? Should we still add it?

**Comment by munirkamal** [comment]
@simonhammes 

Yeah noticed that and so we may avoid using it for now. The Border radius option has already been added. I may close this issue for now. 😇🙌
