### ISSUE TITLE
Submitting form - hiding the form.

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#73]
As I just submitted a form I see a message below the form.

![Screen Shot 2020-03-26 at 16 36 00](https://user-images.githubusercontent.com/5323259/77665640-3b52ca80-6f80-11ea-95dd-77969b133d35.png)

It would be nice with an option to hide. Just below the "Success Message" field.
A checkbox that says something like: "Hide form after successful submission."

![Screen Shot 2020-03-26 at 16 38 55](https://user-images.githubusercontent.com/5323259/77665701-4d346d80-6f80-11ea-90fd-133b72606027.png)

**Comment by ZafarKamal123** [comment]
**Good Suggestion** 👍, I have included a Small Toggle under Success Message to hide the form when submitted!

**Comment by macemmek** [comment]
Hello @ZafarKamal123,

I've set the form to be hidden after submission, but the form does not get hidden.

**Comment by paaljoachim** [comment]
Testing using 1.0.3
Chrome
Local dev site
WP 5.4
Gutenberg plugin 8.1.0 RC

I am also not seeing the form become hidden after I have turn on 
"Hide Form On Success."

**Comment by ZafarKamal123** [comment]
This issue has been fixed now.
