### ISSUE TITLE
User submitting a form.

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#74]
I was just now testing out the contact form on one of my dev sites:
https://webkonsulenten.com/contact/

Then began checking my e-mail to see if I had received any form. But nothing showed up.

Clicked the Gutenberg Forms and checked the sidebar for any location to where a mention of receiver e-mail address would be listed. I did not find any. 

Under Success message there can be a button icon that says open Email Builder to configure who gets the e-mail and what it looks like or something like that. The user then clicks the Email Builder icon also seen here, as well as in the toolbar. It is very easy to overlook the icon in the toolbar.

**Ahhh I there is text that says Email notification builder. I had to turn it on. To enter the email builder.*

![Screen Shot 2020-03-26 at 16 44 58](https://user-images.githubusercontent.com/5323259/77666671-85887b80-6f81-11ea-97e8-38dddab37e0d.png)

The Email builder should already be pre-filled with the various information. The user can just go in and adjust it if needed. Such as admin e-mail address and the fields added to the form. 
(I can if needed add a separate issue for it.)

![Screen Shot 2020-03-26 at 16 48 36](https://user-images.githubusercontent.com/5323259/77666822-b799dd80-6f81-11ea-90d4-b2cbf748a628.png)

---------

I added my e-mail address. Filled in the Name, Email and message field.
I filled in the above and I am waiting for the e-mail to arrive.

I installed Autoptimize plugin to be sure to have refreshed the cache.

----

I went back to the Email Builder and noticed where is a save button. I clicked it.
As I expected that it would automatically save.

-----

Tried to send the form again.
Waiting for an e-mail.

----

I am doing something wrong as the e-mail never showed up....

**Comment by ZafarKamal123** [comment]
Thanks for noticing this huge bug 👀. This has been fixed now!
