### ISSUE TITLE
Prefilling Email builder with e-mail and blocks used in the form

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#76]
The Email builder should already be pre-filled with the various information. The user can just go in and adjust it if needed. Such as admin e-mail address and the fields added to the form.

![Screen Shot 2020-03-27 at 13 58 23](https://user-images.githubusercontent.com/5323259/77758326-0c496100-7033-11ea-88d7-88587b3d4596.png)

**Comment by munirkamal** [comment]
Maybe we can simply have a {summary} or {all_data} tag and keep it added by default. That will pull all the form fields submitted.

**Comment by paaljoachim** [comment]
Having a summary tag automatically added by default sounds good.
Then the user can choose to go in and remove the summary and manually add the fields instead if the user wants to do so.

**Comment by ZafarKamal123** [comment]
✔ I've included another tag **{{all_data}}** which can be used to insert all the fields with their respective values in the email. You can also select this from the **dropdown** above the email builder. 

![added_all_data_tag](https://user-images.githubusercontent.com/48084051/79352182-f43e7080-7f52-11ea-85dd-6f3a86aa7912.PNG)

**Comment by paaljoachim** [comment]
Having the Email Notification in the sidebar is consistent with other settings.
But there is less space to the Email Notification than having it in the Email Builder in the layout area.

That means there could be two versions. One simple as having it in the sidebar, and a more complex Email Builder button below (later on) that opens the Email Builder seen in the layout below the toolbar.

Simple - new sidebar Email Notification area.

NB. to -> To (redo to with To - capital letter).

Advanced - Email Builder.
Containing 
To + CC + BCC field.
Subject
Body with customizations in making the admin submission email look more pretty. As that can be very practical for longer e-mail submissions. It gives more space to customize the body area of the email builder.

**Comment by munirkamal** [comment]
@paaljoachim 

Yeah for a more advanced email designer we may think about something different, and that probably be a pro addon or in pro version to be fair.

For now, I also think of moving it to the sidebar area as it is now is a good way. 

Regarding the CC, BCC, etc that can already be added in the sidebar we have enough space for that.

Cheers

**Comment by paaljoachim** [comment]
Munir I happen to post here first and then I copied my response to https://github.com/munirkamal/gutenberg-forms/issues/98
