### ISSUE TITLE
Email Builder reverts to default values.

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#77]
I noticed when filling in the Email builder. Clicking Save.

![Screen Shot 2020-03-27 at 14 23 35](https://user-images.githubusercontent.com/5323259/77760502-c1314d00-7036-11ea-8e75-231f40c5f064.png)

Then viewing the page on the frontend, submitting a form and then going back to the backend and opening the email builder again that the email builder reverts to default values.

![Screen Shot 2020-03-27 at 14 24 28](https://user-images.githubusercontent.com/5323259/77760509-c42c3d80-7036-11ea-9f9a-56a79597e3c3.png)

**Comment by ZafarKamal123** [comment]
This has been fixed now!
