### ISSUE TITLE
Maximum Length - default to off

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#79]
Here is the maximum set to 100 characters. I did not notice this and tried to send more then 100 characters in the message field but that did not work. I then checked the backend and noticed the below.

Please have max length default to blank.
If the user needs to limit the maximum they can then set an amount of characters.

**Btw at the same time change the maximum limit from 100 to 300.**

![Screen Shot 2020-03-27 at 14 35 36](https://user-images.githubusercontent.com/5323259/77761408-4b2de580-7038-11ea-918f-658a3e3c2820.png)

**Comment by ZafarKamal123** [comment]
I've updated this in the latest commit, The maximum length is set to 1000 by default!

**Comment by paaljoachim** [comment]
Even better!
