### ISSUE TITLE
Example of fields used in Caldera Forms

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#8]
Basic
<img width="724" alt="Screen Shot 2020-02-13 at 17 53 25" src="https://user-images.githubusercontent.com/5323259/74458276-befd9f80-4e89-11ea-9d82-45f53fb700eb.png">

Select
<img width="732" alt="Screen Shot 2020-02-13 at 17 53 56" src="https://user-images.githubusercontent.com/5323259/74458354-db014100-4e89-11ea-8512-783383c04045.png">

File
<img width="729" alt="Screen Shot 2020-02-13 at 17 54 28" src="https://user-images.githubusercontent.com/5323259/74458376-e5bbd600-4e89-11ea-99a8-abf8185f4183.png">

Content
<img width="718" alt="Screen Shot 2020-02-14 at 10 24 45" src="https://user-images.githubusercontent.com/5323259/74518519-45f75a00-4f14-11ea-8b9a-d103c93dfbfd.png">

eCommerce
<img width="738" alt="Screen Shot 2020-02-13 at 17 55 03" src="https://user-images.githubusercontent.com/5323259/74458438-ff5d1d80-4e89-11ea-91e4-517cdade69d8.png">

Special
<img width="723" alt="Screen Shot 2020-02-13 at 17 55 41" src="https://user-images.githubusercontent.com/5323259/74458495-1439b100-4e8a-11ea-91d6-22124f968eba.png">

Example of a Toggle. I was helping Easy Updates Manager and used Caldera Forms to visualize settings they were thinking about adding. They also built a similar UI for their plugin.
https://github.com/easy-updates-manager/easy-updates-manager/issues/202

We can talk through various fields. To see which would be beneficial to add.

**Comment by munirkamal** [comment]
Thanks for sharing. I will look into what new field types should be added to the free version just now. Any specific one you think should be added to the free version just now?

**Comment by paaljoachim** [comment]
Free vs premium. Focus right now on what fields would be helpful. Some fields might have additional options in a future premium plugin.

A toggle switch and a basic file upload can be nice to have.

Many of the others like hr (section break), spacers etc are in the regular block library.
This is an issue we can also come back to when we notice something else that would be helpful to add.

**Comment by munirkamal** [comment]
Toggle Switch (Yes/No) field block added.
