### ISSUE TITLE
LitSpeed Cache plugin affecting forms plugin.

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#81]
Hey

I have a live dev site.
Uses Twenty Twenty.
These plugins are installed and some of them are activated.

![Screen Shot 2020-03-28 at 15 31 36](https://user-images.githubusercontent.com/5323259/77825386-3a997000-7109-11ea-8f08-45b4b7da4ee2.png)

Going to a new page.
Creating a new form. Default style.
![Screen Shot 2020-03-28 at 15 31 08](https://user-images.githubusercontent.com/5323259/77825399-54d34e00-7109-11ea-817a-ea025984fe35.png)

Clicking inline style.
![Screen Shot 2020-03-28 at 15 32 50](https://user-images.githubusercontent.com/5323259/77825418-703e5900-7109-11ea-8e12-c28778e6fb67.png)

Saving the form.
Deactivating LiteSpeed cache.
(After having cleared the cache.)

It looks normal.
![Screen Shot 2020-03-28 at 15 36 49](https://user-images.githubusercontent.com/5323259/77825489-f8bcf980-7109-11ea-878c-aac7f9615c82.png)

**Comment by ZafarKamal123** [comment]
So, The **LiteSpeed cache** plugin changed the styling of the form?

**Comment by paaljoachim** [comment]
Based on my findings above. Yes.
Activate the Twenty Twenty theme and then add new plugin and write LiteSpeed Cache. Install and activate it and then see if the same things happens for your test site. As in affects the styling of the form.

**Comment by paaljoachim** [comment]
I am closing this for now, and will retest at a later time.
