### ISSUE TITLE
When Border radius slider is blank the slider should be all the way to the left.

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#85]
Hey

This is similar to another issue where the slider when blank is halfway. Here is one for multistep.

![Screen Shot 2020-03-30 at 11 13 21](https://user-images.githubusercontent.com/5323259/77895930-c6c9a580-7277-11ea-9745-68ba1e491a3e.png)

When a slider is blank the slider should be all the way to the left.

**Comment by simonhammes** [comment]
Setting the `initialPosition` property to `0` fixes the slider position. Then, it is all the way to the left by default.  
However, there seems to be an error within Gutenberg when the value of a `RangeControl` component is equal to `0`: the input field next to the slider is empty :/

I have added a comment over here: https://github.com/WordPress/gutenberg/issues/20236
