### ISSUE TITLE
Testing out Multistep - under progress -

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#86]
Initial screen.
![Screen Shot 2020-03-29 at 23 16 25](https://user-images.githubusercontent.com/5323259/77895398-017f0e00-7277-11ea-8816-f123ca5e6efd.png)

Selecting multistep.
One sees two multistep areas.

![Screen Shot 2020-03-30 at 11 11 14](https://user-images.githubusercontent.com/5323259/77895547-3c814180-7277-11ea-89d4-2cd4971a83db.png)

Adding blocks into our outside the multistep.

One can add a formstep (should it stick with the name Multistep?) block.
![Screen Shot 2020-03-30 at 11 17 06](https://user-images.githubusercontent.com/5323259/77896234-3d66a300-7278-11ea-998c-fdcebffa7dc9.png)

One can add a Gutenberg Forms block.
![Screen Shot 2020-03-30 at 11 17 14](https://user-images.githubusercontent.com/5323259/77896248-46f00b00-7278-11ea-85cd-d3b6a88ad05d.png)

One can also click into an empty area and just add a regular Gutenberg block.
![Screen Shot 2020-03-30 at 11 19 57](https://user-images.githubusercontent.com/5323259/77896350-6be47e00-7278-11ea-90e7-f06475bc3fae.png)

Having three different ways to add blocks is a bit confusing. I will just think out loud....

The three levels: Gutenberg (Document) -> Gutenberg Forms -> Form Step.

1. The names Form Step and Multi Step seems to be mixed.

Tooltips. Hovering over Form Step it would be nice with a tooltip that says Add Multi Step Block.

<img width="797" alt="Screen Shot 2020-03-30 at 11 23 58" src="https://user-images.githubusercontent.com/5323259/77896756-080e8500-7279-11ea-825e-fc1c593f71a6.png">

Hovering over Gutenberg Forms have a tooltip that says Add Gutenberg Forms Block.

Should Gutenberg Forms block area be removed? As we are now inside the Multistep area.
I tried dragging a Multistep block out of the Form Step area. That did not work. So one then needs to have the Gutenberg Forms block outside of the Form Step area. The question is then if one removes the Gutenberg Forms block and one could instead drag a Form step block outside to have a block that is seen in all the steps in addition to having access to the regular Gutenberg blocks.

I will update/edit this issue..... as I continue testing out the multistep.

**Comment by paaljoachim** [comment]
I have gone through and added a bunch of steps, and it looks to be working pretty well.
I added a submit button in the last step.
Clicking the button it then goes here:

<img width="663" alt="Screen Shot 2020-03-30 at 11 47 37" src="https://user-images.githubusercontent.com/5323259/77898971-46597380-727c-11ea-9271-ec25655f1fc9.png">

Here it would be nice with a summary of all fields that have been filled out so one can see all the questions and replies on one page. Actually that would look fairly similar to the e-mail sent.

**Comment by munirkamal** [comment]
Just passing a comment posted by a user at WP Support forum regarding multi-step.

> It was not clear to me how to setup a multistep form, and make its previous/next dynamic work, because there is no indication anywhere that after inserting a form step, I also should insert a separate form button. Don’t get me wrong: I enjoy very much this modular approach – now that I understand it – because I can insert buttons anywhere, in different orders, colors etc. But I was expecting these buttons to come together with every multistep form I insert. 

> (a)Maybe in its settings, either on sidebar or inside the editor. It is just strange how the multistep form block interrelates with settings on another block, but nothing is explained. Maybe it is more of a Gutenberg problem, since it is not easy to visually understand nested blocks, but 


> (b)maybe you also can insert a text line suggesting us to create form buttons after creating a form step. 


> (c)Or a placeholder inside the nested block in the editor (please observe Block Permissions plugin approach to solve this issue)… or (d)insert a form button automatically together with a form step when inserting it. I don’t know which approach is better, but something needs to be done. Otherwise, congratulations. The basic implementation works.
