### ISSUE TITLE
Buttons block seen in Gutenberg.

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#87]
Hey

This is what the buttons block looks like in Gutenberg.
Using Twenty Twenty. (Inserter has a bug for the moment.)

![Screen Shot 2020-03-30 at 11 36 33](https://user-images.githubusercontent.com/5323259/77898035-cc74ba80-727a-11ea-9d03-62d858333ece.png)

![Screen Shot 2020-03-30 at 11 36 58](https://user-images.githubusercontent.com/5323259/77898039-ced71480-727a-11ea-98ca-f32a960620e0.png)

In regards to multistep. It would be helpful to add it like the above. As one could have in the backend a Next and a Previous button. I have noticed one can add two buttons one below the other and that also works alright.

**Comment by munirkamal** [comment]
This will complicate the form button block. Users can simply add two blocks and set alignment to left for the first one which will make two buttons inline.

@paaljoachim 
Please test if that is possible that way, if so, let's close this issue?

**Comment by paaljoachim** [comment]
Yeah. One can add one button after another and the show up in a line. Closing this issue.
