### ISSUE TITLE
A conditionals group block?

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#9]
I am thinking out loud...

Lets say that I need to add some conditionals such as..

A drop down. 
- Customer Service
- Support
- Feedback
- Other

User selects **Support**.
Additional fields open that have to do with support.

Checkboxes:
1. Product A.
2. Product B.
3. Product C.

Paragraph field - Give us feedback to the product you are using.

---

Let's say that there is a Gutenberg Forms group block that also contains conditionals.
Meaning any field added to the group block will have additional sidebar options that include conditionals.

That could mean click the drop down. Have options in the sidebar.
Select option Support. Choose: Show/hide/disable. I selected Show.
Then the list of all the fields are seen. One would then make a multi select choosing 1 or more fields. That are seen when user selects Support. That means they start out as hidden and are seen at the moment user selects Support.

**Comment by munirkamal** [comment]
Conditional Login would potentially be a premium feature so we may look into this later. What do you think?

**Comment by paaljoachim** [comment]
I think that we need to set the premium version aside for now and focus on creating a top free plugin. Drawing users to the plugin. As more and more use the plugin users will ask for additional features. At that time one can then begin to think of which feature would be natural to add into a premium and which would be natural to add to the free version.

Right now think of everything like premium or everything like free. Whatever motivates you best..:)

The focus is on creating the best plugin one can. For there might be some conditionals in the free and even better conditionals in the premium. As a user I use a plugin and if I really like it I will naturally begin to see what the premium offers. If it is an upgraded experience I might then purchase the premium just because it offers more of what I already like.

Btw many will also prefer the premium because of the additional quick support they will likely get.

**Comment by munirkamal** [comment]
As per your feedback, I have added basic conditional logic to the free version. 😇
The "Form Group" block may also be triggered conditionally.

**Comment by paaljoachim** [comment]
That is great Munir! Conditionals is actually one important feature for people. One argument for someone to select using Gutenberg Forms. 

Premium is offering more of various features that a user has gradually began to use in the free version.

There will be more then enough reasons later on for people to want to upgrade to the premium version. We will both take care of that..:)
