### ISSUE TITLE
Easier to access submission/email builder area.

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#98]
It is hard to discover that clicking the Email Builder opens the Email Builder area.

<img width="162" alt="Screen Shot 2020-04-13 at 21 46 13" src="https://user-images.githubusercontent.com/5323259/79154658-37bca180-7dd0-11ea-82a4-338e1011ce77.png">

Email Builder.
<img width="1086" alt="Screen Shot 2020-04-13 at 21 47 05" src="https://user-images.githubusercontent.com/5323259/79154712-56bb3380-7dd0-11ea-8917-95a05614e445.png">

That is weird.... Styles for the Email Builder is really not needed as I understand it. It is there only so that we can add the Field Data seen in the e-mail the admin etc receives.

---

There could be a quick area in the regular sidebar. Called Submissions/Email Builder.

<img width="1077" alt="Screen Shot 2020-04-13 at 21 48 47" src="https://user-images.githubusercontent.com/5323259/79154874-95e98480-7dd0-11ea-8700-ba37852f8910.png">

It could contain receiving e-mail field, and then a link to open the Email builder.

As it would make the Email Builder easier to find.

**Comment by munirkamal** [comment]
@paaljoachim 
You are right, I think we might need to revisit how/where to set up this email notification stuff. Adding it to the To-Do now. 

Note for @ZafarKamal123 
Let's re-think how best to handle this that minimizes confusion and easier to access and use.

**Comment by ZafarKamal123** [comment]
I've moved the **Email Notification Builder** into a separate panel in the sidebar. This is under development version currently. You can check the commit 0867a61 .

Here's a quick snapshot.

![moved_email_builder_to_sidebar](https://user-images.githubusercontent.com/48084051/79345535-ad4c7d00-7f4a-11ea-85b0-db312a405f30.PNG)

Let me know what you think about it @paaljoachim 👍

**Comment by munirkamal** [comment]
@paaljoachim @simonhammes 

Kindly test the master branch if you got time and pass your feedback on this. The thing we have done is to move the email builder to the sidebar for the sake of simplicity and easy for the users.

Let me know what you think of this?

**Comment by paaljoachim** [comment]
Having the Email Notification in the sidebar is consistent with other settings.
But there is less space to the Email Notification than having it in the Email Builder in the layout area.

A thought....
That means there could be two versions. One simple as having it in the sidebar, and a more complex Email Builder button below (later on) that opens the Email Builder seen in the layout below the toolbar.

Simple - new sidebar Email Notification area.

NB. to -> To (redo to with To - capital letter).

Advanced - Email Builder.
Containing
To + CC + BCC field.
Subject
Body with customizations in making the admin submission email look more pretty. As that can be very practical for longer e-mail submissions. It gives more space to customize the body area of the email builder.

**Comment by paaljoachim** [comment]
I agree with Munir's comment https://github.com/munirkamal/gutenberg-forms/issues/76#issuecomment-614127428

"Yeah for a more advanced email designer we may think about something different, and that probably be a pro addon or in pro version to be fair."

Sounds like a good idea to have it in a pro version.

**Comment by simonhammes** [comment]
> Kindly test the master branch if you got time and pass your feedback on this. The thing we have done is to move the email builder to the sidebar for the sake of simplicity and easy for the users.

Works well! :+1:  I am not a huge fan of the sidebar being a bit cluttered, but I understand that it makes sense to put it there.

**Comment by paaljoachim** [comment]
I agree Simon. The sidebar is a narrow area with a lot of settings. But it is a natural place to put it alongside the other settings.
