### ISSUE TITLE
Adjustments to the WP menu sidebar - Gutenberg Forms

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#99]
The WP menu sidebar - Gutenberg Forms.

Gutenberg Forms -> Gutenberg Forms
![Screen Shot 2020-04-14 at 00 22 34](https://user-images.githubusercontent.com/5323259/79166723-15358300-7de6-11ea-83ca-5f8a52774353.png)

Clicking the submenu Forms closes the submenu. It instead opens as a flyout.

![Screen Shot 2020-04-14 at 00 24 30](https://user-images.githubusercontent.com/5323259/79166859-5a59b500-7de6-11ea-9382-1e046462a806.png)

Keep the Gutenberg Forms submenu open when selecting any of the submenu items.

I will add another issue for the Gutenberg Forms submenu.

**Comment by simonhammes** [comment]
@paaljoachim Just to clarify:

You want it to behave like this, right?

![screenshot-1](https://user-images.githubusercontent.com/10352679/79210323-f0242d00-7e44-11ea-814a-3e770a73f82a.png)

**Comment by munirkamal** [comment]
Yeah I knew someone will notice it. 🤣
I need to check how to keep it open.

@simonhammes Do you know?

**Comment by simonhammes** [comment]
Yeah I can open a PR later (today), same for the Entries
